// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/dto"
	"github.com/PhantomX7/athleton/internal/modules/auth/service"
)

// Ensure, that AuthServiceMock does implement service.AuthService.
// If this is not the case, regenerate this file with moq.
var _ service.AuthService = &AuthServiceMock{}

// AuthServiceMock is a mock implementation of service.AuthService.
//
//	func TestSomethingThatUsesAuthService(t *testing.T) {
//
//		// make and configure a mocked service.AuthService
//		mockedAuthService := &AuthServiceMock{
//			ChangePasswordFunc: func(ctx context.Context, req *dto.ChangePasswordRequest) error {
//				panic("mock out the ChangePassword method")
//			},
//			GetMeFunc: func(ctx context.Context) (*dto.MeResponse, error) {
//				panic("mock out the GetMe method")
//			},
//			LogoutFunc: func(ctx context.Context, req *dto.LogoutRequest) error {
//				panic("mock out the Logout method")
//			},
//			RefreshFunc: func(ctx context.Context, req *dto.RefreshRequest) (*dto.AuthResponse, error) {
//				panic("mock out the Refresh method")
//			},
//			RegisterFunc: func(ctx context.Context, req *dto.RegisterRequest) (*dto.AuthResponse, error) {
//				panic("mock out the Register method")
//			},
//		}
//
//		// use mockedAuthService in code that requires service.AuthService
//		// and then make assertions.
//
//	}
type AuthServiceMock struct {
	// ChangePasswordFunc mocks the ChangePassword method.
	ChangePasswordFunc func(ctx context.Context, req *dto.ChangePasswordRequest) error

	// GetMeFunc mocks the GetMe method.
	GetMeFunc func(ctx context.Context) (*dto.MeResponse, error)

	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, req *dto.LogoutRequest) error

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, req *dto.RefreshRequest) (*dto.AuthResponse, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, req *dto.RegisterRequest) (*dto.AuthResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChangePassword holds details about calls to the ChangePassword method.
		ChangePassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *dto.ChangePasswordRequest
		}
		// GetMe holds details about calls to the GetMe method.
		GetMe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *dto.LogoutRequest
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *dto.RefreshRequest
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *dto.RegisterRequest
		}
	}
	lockChangePassword sync.RWMutex
	lockGetMe          sync.RWMutex
	lockLogout         sync.RWMutex
	lockRefresh        sync.RWMutex
	lockRegister       sync.RWMutex
}

// ChangePassword calls ChangePasswordFunc.
func (mock *AuthServiceMock) ChangePassword(ctx context.Context, req *dto.ChangePasswordRequest) error {
	if mock.ChangePasswordFunc == nil {
		panic("AuthServiceMock.ChangePasswordFunc: method is nil but AuthService.ChangePassword was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *dto.ChangePasswordRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockChangePassword.Lock()
	mock.calls.ChangePassword = append(mock.calls.ChangePassword, callInfo)
	mock.lockChangePassword.Unlock()
	return mock.ChangePasswordFunc(ctx, req)
}

// ChangePasswordCalls gets all the calls that were made to ChangePassword.
// Check the length with:
//
//	len(mockedAuthService.ChangePasswordCalls())
func (mock *AuthServiceMock) ChangePasswordCalls() []struct {
	Ctx context.Context
	Req *dto.ChangePasswordRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *dto.ChangePasswordRequest
	}
	mock.lockChangePassword.RLock()
	calls = mock.calls.ChangePassword
	mock.lockChangePassword.RUnlock()
	return calls
}

// GetMe calls GetMeFunc.
func (mock *AuthServiceMock) GetMe(ctx context.Context) (*dto.MeResponse, error) {
	if mock.GetMeFunc == nil {
		panic("AuthServiceMock.GetMeFunc: method is nil but AuthService.GetMe was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetMe.Lock()
	mock.calls.GetMe = append(mock.calls.GetMe, callInfo)
	mock.lockGetMe.Unlock()
	return mock.GetMeFunc(ctx)
}

// GetMeCalls gets all the calls that were made to GetMe.
// Check the length with:
//
//	len(mockedAuthService.GetMeCalls())
func (mock *AuthServiceMock) GetMeCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetMe.RLock()
	calls = mock.calls.GetMe
	mock.lockGetMe.RUnlock()
	return calls
}

// Logout calls LogoutFunc.
func (mock *AuthServiceMock) Logout(ctx context.Context, req *dto.LogoutRequest) error {
	if mock.LogoutFunc == nil {
		panic("AuthServiceMock.LogoutFunc: method is nil but AuthService.Logout was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *dto.LogoutRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, req)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedAuthService.LogoutCalls())
func (mock *AuthServiceMock) LogoutCalls() []struct {
	Ctx context.Context
	Req *dto.LogoutRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *dto.LogoutRequest
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *AuthServiceMock) Refresh(ctx context.Context, req *dto.RefreshRequest) (*dto.AuthResponse, error) {
	if mock.RefreshFunc == nil {
		panic("AuthServiceMock.RefreshFunc: method is nil but AuthService.Refresh was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *dto.RefreshRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, req)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedAuthService.RefreshCalls())
func (mock *AuthServiceMock) RefreshCalls() []struct {
	Ctx context.Context
	Req *dto.RefreshRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *dto.RefreshRequest
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *AuthServiceMock) Register(ctx context.Context, req *dto.RegisterRequest) (*dto.AuthResponse, error) {
	if mock.RegisterFunc == nil {
		panic("AuthServiceMock.RegisterFunc: method is nil but AuthService.Register was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *dto.RegisterRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, req)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedAuthService.RegisterCalls())
func (mock *AuthServiceMock) RegisterCalls() []struct {
	Ctx context.Context
	Req *dto.RegisterRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *dto.RegisterRequest
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}
