// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/dto"
	"github.com/PhantomX7/athleton/internal/models"
	"github.com/PhantomX7/athleton/internal/modules/admin_role/service"
	"github.com/PhantomX7/athleton/pkg/pagination"
	"github.com/PhantomX7/athleton/pkg/response"
)

// Ensure, that AdminRoleServiceMock does implement service.AdminRoleService.
// If this is not the case, regenerate this file with moq.
var _ service.AdminRoleService = &AdminRoleServiceMock{}

// AdminRoleServiceMock is a mock implementation of service.AdminRoleService.
//
//	func TestSomethingThatUsesAdminRoleService(t *testing.T) {
//
//		// make and configure a mocked service.AdminRoleService
//		mockedAdminRoleService := &AdminRoleServiceMock{
//			CreateFunc: func(ctx context.Context, req *dto.CreateAdminRoleRequest) (*models.AdminRole, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, roleID uint) error {
//				panic("mock out the Delete method")
//			},
//			FindByIDFunc: func(ctx context.Context, roleID uint) (*models.AdminRole, error) {
//				panic("mock out the FindByID method")
//			},
//			GetAllPermissionsFunc: func(ctx context.Context) map[string][]map[string]string {
//				panic("mock out the GetAllPermissions method")
//			},
//			IndexFunc: func(ctx context.Context, req *pagination.Pagination) ([]*models.AdminRole, response.Meta, error) {
//				panic("mock out the Index method")
//			},
//			UpdateFunc: func(ctx context.Context, roleID uint, req *dto.UpdateAdminRoleRequest) (*models.AdminRole, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedAdminRoleService in code that requires service.AdminRoleService
//		// and then make assertions.
//
//	}
type AdminRoleServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, req *dto.CreateAdminRoleRequest) (*models.AdminRole, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, roleID uint) error

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, roleID uint) (*models.AdminRole, error)

	// GetAllPermissionsFunc mocks the GetAllPermissions method.
	GetAllPermissionsFunc func(ctx context.Context) map[string][]map[string]string

	// IndexFunc mocks the Index method.
	IndexFunc func(ctx context.Context, req *pagination.Pagination) ([]*models.AdminRole, response.Meta, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, roleID uint, req *dto.UpdateAdminRoleRequest) (*models.AdminRole, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *dto.CreateAdminRoleRequest
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID uint
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID uint
		}
		// GetAllPermissions holds details about calls to the GetAllPermissions method.
		GetAllPermissions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *pagination.Pagination
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID uint
			// Req is the req argument value.
			Req *dto.UpdateAdminRoleRequest
		}
	}
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockFindByID          sync.RWMutex
	lockGetAllPermissions sync.RWMutex
	lockIndex             sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Create calls CreateFunc.
func (mock *AdminRoleServiceMock) Create(ctx context.Context, req *dto.CreateAdminRoleRequest) (*models.AdminRole, error) {
	if mock.CreateFunc == nil {
		panic("AdminRoleServiceMock.CreateFunc: method is nil but AdminRoleService.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *dto.CreateAdminRoleRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAdminRoleService.CreateCalls())
func (mock *AdminRoleServiceMock) CreateCalls() []struct {
	Ctx context.Context
	Req *dto.CreateAdminRoleRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *dto.CreateAdminRoleRequest
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *AdminRoleServiceMock) Delete(ctx context.Context, roleID uint) error {
	if mock.DeleteFunc == nil {
		panic("AdminRoleServiceMock.DeleteFunc: method is nil but AdminRoleService.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID uint
	}{
		Ctx:    ctx,
		RoleID: roleID,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, roleID)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAdminRoleService.DeleteCalls())
func (mock *AdminRoleServiceMock) DeleteCalls() []struct {
	Ctx    context.Context
	RoleID uint
} {
	var calls []struct {
		Ctx    context.Context
		RoleID uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *AdminRoleServiceMock) FindByID(ctx context.Context, roleID uint) (*models.AdminRole, error) {
	if mock.FindByIDFunc == nil {
		panic("AdminRoleServiceMock.FindByIDFunc: method is nil but AdminRoleService.FindByID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID uint
	}{
		Ctx:    ctx,
		RoleID: roleID,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, roleID)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedAdminRoleService.FindByIDCalls())
func (mock *AdminRoleServiceMock) FindByIDCalls() []struct {
	Ctx    context.Context
	RoleID uint
} {
	var calls []struct {
		Ctx    context.Context
		RoleID uint
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// GetAllPermissions calls GetAllPermissionsFunc.
func (mock *AdminRoleServiceMock) GetAllPermissions(ctx context.Context) map[string][]map[string]string {
	if mock.GetAllPermissionsFunc == nil {
		panic("AdminRoleServiceMock.GetAllPermissionsFunc: method is nil but AdminRoleService.GetAllPermissions was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAllPermissions.Lock()
	mock.calls.GetAllPermissions = append(mock.calls.GetAllPermissions, callInfo)
	mock.lockGetAllPermissions.Unlock()
	return mock.GetAllPermissionsFunc(ctx)
}

// GetAllPermissionsCalls gets all the calls that were made to GetAllPermissions.
// Check the length with:
//
//	len(mockedAdminRoleService.GetAllPermissionsCalls())
func (mock *AdminRoleServiceMock) GetAllPermissionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAllPermissions.RLock()
	calls = mock.calls.GetAllPermissions
	mock.lockGetAllPermissions.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *AdminRoleServiceMock) Index(ctx context.Context, req *pagination.Pagination) ([]*models.AdminRole, response.Meta, error) {
	if mock.IndexFunc == nil {
		panic("AdminRoleServiceMock.IndexFunc: method is nil but AdminRoleService.Index was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *pagination.Pagination
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(ctx, req)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedAdminRoleService.IndexCalls())
func (mock *AdminRoleServiceMock) IndexCalls() []struct {
	Ctx context.Context
	Req *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Req *pagination.Pagination
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *AdminRoleServiceMock) Update(ctx context.Context, roleID uint, req *dto.UpdateAdminRoleRequest) (*models.AdminRole, error) {
	if mock.UpdateFunc == nil {
		panic("AdminRoleServiceMock.UpdateFunc: method is nil but AdminRoleService.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID uint
		Req    *dto.UpdateAdminRoleRequest
	}{
		Ctx:    ctx,
		RoleID: roleID,
		Req:    req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, roleID, req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedAdminRoleService.UpdateCalls())
func (mock *AdminRoleServiceMock) UpdateCalls() []struct {
	Ctx    context.Context
	RoleID uint
	Req    *dto.UpdateAdminRoleRequest
} {
	var calls []struct {
		Ctx    context.Context
		RoleID uint
		Req    *dto.UpdateAdminRoleRequest
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
