// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/models"
	"github.com/PhantomX7/athleton/internal/modules/log/service"
	"github.com/PhantomX7/athleton/pkg/pagination"
	"github.com/PhantomX7/athleton/pkg/response"
)

// Ensure, that LogServiceMock does implement service.LogService.
// If this is not the case, regenerate this file with moq.
var _ service.LogService = &LogServiceMock{}

// LogServiceMock is a mock implementation of service.LogService.
//
//	func TestSomethingThatUsesLogService(t *testing.T) {
//
//		// make and configure a mocked service.LogService
//		mockedLogService := &LogServiceMock{
//			FindByIDFunc: func(ctx context.Context, logID uint) (*models.Log, error) {
//				panic("mock out the FindByID method")
//			},
//			IndexFunc: func(ctx context.Context, req *pagination.Pagination) ([]*models.Log, response.Meta, error) {
//				panic("mock out the Index method")
//			},
//		}
//
//		// use mockedLogService in code that requires service.LogService
//		// and then make assertions.
//
//	}
type LogServiceMock struct {
	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, logID uint) (*models.Log, error)

	// IndexFunc mocks the Index method.
	IndexFunc func(ctx context.Context, req *pagination.Pagination) ([]*models.Log, response.Meta, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LogID is the logID argument value.
			LogID uint
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *pagination.Pagination
		}
	}
	lockFindByID sync.RWMutex
	lockIndex    sync.RWMutex
}

// FindByID calls FindByIDFunc.
func (mock *LogServiceMock) FindByID(ctx context.Context, logID uint) (*models.Log, error) {
	if mock.FindByIDFunc == nil {
		panic("LogServiceMock.FindByIDFunc: method is nil but LogService.FindByID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		LogID uint
	}{
		Ctx:   ctx,
		LogID: logID,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, logID)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedLogService.FindByIDCalls())
func (mock *LogServiceMock) FindByIDCalls() []struct {
	Ctx   context.Context
	LogID uint
} {
	var calls []struct {
		Ctx   context.Context
		LogID uint
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *LogServiceMock) Index(ctx context.Context, req *pagination.Pagination) ([]*models.Log, response.Meta, error) {
	if mock.IndexFunc == nil {
		panic("LogServiceMock.IndexFunc: method is nil but LogService.Index was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *pagination.Pagination
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(ctx, req)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedLogService.IndexCalls())
func (mock *LogServiceMock) IndexCalls() []struct {
	Ctx context.Context
	Req *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Req *pagination.Pagination
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}
