// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/models"
	refreshtokenrepository "github.com/PhantomX7/athleton/internal/modules/refresh_token/repository"
	"github.com/PhantomX7/athleton/pkg/pagination"
	pkgrepository "github.com/PhantomX7/athleton/pkg/repository"
	"github.com/google/uuid"
)

// Ensure, that RefreshTokenRepositoryMock does implement refreshtokenrepository.RefreshTokenRepository.
// If this is not the case, regenerate this file with moq.
var _ refreshtokenrepository.RefreshTokenRepository = &RefreshTokenRepositoryMock{}

// RefreshTokenRepositoryMock is a mock implementation of refreshtokenrepository.RefreshTokenRepository.
//
//	func TestSomethingThatUsesRefreshTokenRepository(t *testing.T) {
//
//		// make and configure a mocked refreshtokenrepository.RefreshTokenRepository
//		mockedRefreshTokenRepository := &RefreshTokenRepositoryMock{
//			CountFunc: func(ctx context.Context, pg *pagination.Pagination) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, entity *models.RefreshToken) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, entity *models.RefreshToken) error {
//				panic("mock out the Delete method")
//			},
//			DeleteInvalidTokenFunc: func(ctx context.Context) error {
//				panic("mock out the DeleteInvalidToken method")
//			},
//			FindActiveByIDFunc: func(ctx context.Context, id uuid.UUID) (*models.RefreshToken, error) {
//				panic("mock out the FindActiveByID method")
//			},
//			FindAllFunc: func(ctx context.Context, pg *pagination.Pagination) ([]*models.RefreshToken, error) {
//				panic("mock out the FindAll method")
//			},
//			FindByIDFunc: func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.RefreshToken, error) {
//				panic("mock out the FindByID method")
//			},
//			FindByPreviousTokenFunc: func(ctx context.Context, token string) (*models.RefreshToken, error) {
//				panic("mock out the FindByPreviousToken method")
//			},
//			FindByTokenFunc: func(ctx context.Context, token string) (*models.RefreshToken, error) {
//				panic("mock out the FindByToken method")
//			},
//			GetValidCountByUserIDFunc: func(ctx context.Context, userID uint) (int64, error) {
//				panic("mock out the GetValidCountByUserID method")
//			},
//			RevokeAllByUserIDFunc: func(ctx context.Context, userID uint) error {
//				panic("mock out the RevokeAllByUserID method")
//			},
//			RevokeAllByUserIDExceptFunc: func(ctx context.Context, userID uint, exceptToken string) error {
//				panic("mock out the RevokeAllByUserIDExcept method")
//			},
//			RevokeByTokenFunc: func(ctx context.Context, token string) error {
//				panic("mock out the RevokeByToken method")
//			},
//			RevokeByTokenIfActiveFunc: func(ctx context.Context, token string) (bool, error) {
//				panic("mock out the RevokeByTokenIfActive method")
//			},
//			RevokeOldestActiveByUserIDFunc: func(ctx context.Context, userID uint, n int) error {
//				panic("mock out the RevokeOldestActiveByUserID method")
//			},
//			UpdateFunc: func(ctx context.Context, entity *models.RefreshToken) error {
//				panic("mock out the Update method")
//			},
//			UpdateTokenHashIfActiveFunc: func(ctx context.Context, oldToken string, newToken string) (bool, error) {
//				panic("mock out the UpdateTokenHashIfActive method")
//			},
//		}
//
//		// use mockedRefreshTokenRepository in code that requires refreshtokenrepository.RefreshTokenRepository
//		// and then make assertions.
//
//	}
type RefreshTokenRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, pg *pagination.Pagination) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *models.RefreshToken) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, entity *models.RefreshToken) error

	// DeleteInvalidTokenFunc mocks the DeleteInvalidToken method.
	DeleteInvalidTokenFunc func(ctx context.Context) error

	// FindActiveByIDFunc mocks the FindActiveByID method.
	FindActiveByIDFunc func(ctx context.Context, id uuid.UUID) (*models.RefreshToken, error)

	// FindAllFunc mocks the FindAll method.
	FindAllFunc func(ctx context.Context, pg *pagination.Pagination) ([]*models.RefreshToken, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.RefreshToken, error)

	// FindByPreviousTokenFunc mocks the FindByPreviousToken method.
	FindByPreviousTokenFunc func(ctx context.Context, token string) (*models.RefreshToken, error)

	// FindByTokenFunc mocks the FindByToken method.
	FindByTokenFunc func(ctx context.Context, token string) (*models.RefreshToken, error)

	// GetValidCountByUserIDFunc mocks the GetValidCountByUserID method.
	GetValidCountByUserIDFunc func(ctx context.Context, userID uint) (int64, error)

	// RevokeAllByUserIDFunc mocks the RevokeAllByUserID method.
	RevokeAllByUserIDFunc func(ctx context.Context, userID uint) error

	// RevokeAllByUserIDExceptFunc mocks the RevokeAllByUserIDExcept method.
	RevokeAllByUserIDExceptFunc func(ctx context.Context, userID uint, exceptToken string) error

	// RevokeByTokenFunc mocks the RevokeByToken method.
	RevokeByTokenFunc func(ctx context.Context, token string) error

	// RevokeByTokenIfActiveFunc mocks the RevokeByTokenIfActive method.
	RevokeByTokenIfActiveFunc func(ctx context.Context, token string) (bool, error)

	// RevokeOldestActiveByUserIDFunc mocks the RevokeOldestActiveByUserID method.
	RevokeOldestActiveByUserIDFunc func(ctx context.Context, userID uint, n int) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, entity *models.RefreshToken) error

	// UpdateTokenHashIfActiveFunc mocks the UpdateTokenHashIfActive method.
	UpdateTokenHashIfActiveFunc func(ctx context.Context, oldToken string, newToken string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.RefreshToken
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.RefreshToken
		}
		// DeleteInvalidToken holds details about calls to the DeleteInvalidToken method.
		DeleteInvalidToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// FindActiveByID holds details about calls to the FindActiveByID method.
		FindActiveByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
			// Preloads is the preloads argument value.
			Preloads []pkgrepository.Association
		}
		// FindByPreviousToken holds details about calls to the FindByPreviousToken method.
		FindByPreviousToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// FindByToken holds details about calls to the FindByToken method.
		FindByToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// GetValidCountByUserID holds details about calls to the GetValidCountByUserID method.
		GetValidCountByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
		}
		// RevokeAllByUserID holds details about calls to the RevokeAllByUserID method.
		RevokeAllByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
		}
		// RevokeAllByUserIDExcept holds details about calls to the RevokeAllByUserIDExcept method.
		RevokeAllByUserIDExcept []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
			// ExceptToken is the exceptToken argument value.
			ExceptToken string
		}
		// RevokeByToken holds details about calls to the RevokeByToken method.
		RevokeByToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// RevokeByTokenIfActive holds details about calls to the RevokeByTokenIfActive method.
		RevokeByTokenIfActive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// RevokeOldestActiveByUserID holds details about calls to the RevokeOldestActiveByUserID method.
		RevokeOldestActiveByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
			// N is the n argument value.
			N int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.RefreshToken
		}
		// UpdateTokenHashIfActive holds details about calls to the UpdateTokenHashIfActive method.
		UpdateTokenHashIfActive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldToken is the oldToken argument value.
			OldToken string
			// NewToken is the newToken argument value.
			NewToken string
		}
	}
	lockCount                      sync.RWMutex
	lockCreate                     sync.RWMutex
	lockDelete                     sync.RWMutex
	lockDeleteInvalidToken         sync.RWMutex
	lockFindActiveByID             sync.RWMutex
	lockFindAll                    sync.RWMutex
	lockFindByID                   sync.RWMutex
	lockFindByPreviousToken        sync.RWMutex
	lockFindByToken                sync.RWMutex
	lockGetValidCountByUserID      sync.RWMutex
	lockRevokeAllByUserID          sync.RWMutex
	lockRevokeAllByUserIDExcept    sync.RWMutex
	lockRevokeByToken              sync.RWMutex
	lockRevokeByTokenIfActive      sync.RWMutex
	lockRevokeOldestActiveByUserID sync.RWMutex
	lockUpdate                     sync.RWMutex
	lockUpdateTokenHashIfActive    sync.RWMutex
}

// Count calls CountFunc.
func (mock *RefreshTokenRepositoryMock) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	if mock.CountFunc == nil {
		panic("RefreshTokenRepositoryMock.CountFunc: method is nil but RefreshTokenRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, pg)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.CountCalls())
func (mock *RefreshTokenRepositoryMock) CountCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *RefreshTokenRepositoryMock) Create(ctx context.Context, entity *models.RefreshToken) error {
	if mock.CreateFunc == nil {
		panic("RefreshTokenRepositoryMock.CreateFunc: method is nil but RefreshTokenRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.RefreshToken
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.CreateCalls())
func (mock *RefreshTokenRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *models.RefreshToken
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.RefreshToken
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RefreshTokenRepositoryMock) Delete(ctx context.Context, entity *models.RefreshToken) error {
	if mock.DeleteFunc == nil {
		panic("RefreshTokenRepositoryMock.DeleteFunc: method is nil but RefreshTokenRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.RefreshToken
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, entity)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.DeleteCalls())
func (mock *RefreshTokenRepositoryMock) DeleteCalls() []struct {
	Ctx    context.Context
	Entity *models.RefreshToken
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.RefreshToken
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// DeleteInvalidToken calls DeleteInvalidTokenFunc.
func (mock *RefreshTokenRepositoryMock) DeleteInvalidToken(ctx context.Context) error {
	if mock.DeleteInvalidTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.DeleteInvalidTokenFunc: method is nil but RefreshTokenRepository.DeleteInvalidToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDeleteInvalidToken.Lock()
	mock.calls.DeleteInvalidToken = append(mock.calls.DeleteInvalidToken, callInfo)
	mock.lockDeleteInvalidToken.Unlock()
	return mock.DeleteInvalidTokenFunc(ctx)
}

// DeleteInvalidTokenCalls gets all the calls that were made to DeleteInvalidToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.DeleteInvalidTokenCalls())
func (mock *RefreshTokenRepositoryMock) DeleteInvalidTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDeleteInvalidToken.RLock()
	calls = mock.calls.DeleteInvalidToken
	mock.lockDeleteInvalidToken.RUnlock()
	return calls
}

// FindActiveByID calls FindActiveByIDFunc.
func (mock *RefreshTokenRepositoryMock) FindActiveByID(ctx context.Context, id uuid.UUID) (*models.RefreshToken, error) {
	if mock.FindActiveByIDFunc == nil {
		panic("RefreshTokenRepositoryMock.FindActiveByIDFunc: method is nil but RefreshTokenRepository.FindActiveByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindActiveByID.Lock()
	mock.calls.FindActiveByID = append(mock.calls.FindActiveByID, callInfo)
	mock.lockFindActiveByID.Unlock()
	return mock.FindActiveByIDFunc(ctx, id)
}

// FindActiveByIDCalls gets all the calls that were made to FindActiveByID.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.FindActiveByIDCalls())
func (mock *RefreshTokenRepositoryMock) FindActiveByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockFindActiveByID.RLock()
	calls = mock.calls.FindActiveByID
	mock.lockFindActiveByID.RUnlock()
	return calls
}

// FindAll calls FindAllFunc.
func (mock *RefreshTokenRepositoryMock) FindAll(ctx context.Context, pg *pagination.Pagination) ([]*models.RefreshToken, error) {
	if mock.FindAllFunc == nil {
		panic("RefreshTokenRepositoryMock.FindAllFunc: method is nil but RefreshTokenRepository.FindAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	mock.lockFindAll.Unlock()
	return mock.FindAllFunc(ctx, pg)
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.FindAllCalls())
func (mock *RefreshTokenRepositoryMock) FindAllCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockFindAll.RLock()
	calls = mock.calls.FindAll
	mock.lockFindAll.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *RefreshTokenRepositoryMock) FindByID(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.RefreshToken, error) {
	if mock.FindByIDFunc == nil {
		panic("RefreshTokenRepositoryMock.FindByIDFunc: method is nil but RefreshTokenRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}{
		Ctx:      ctx,
		ID:       id,
		Preloads: preloads,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id, preloads...)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.FindByIDCalls())
func (mock *RefreshTokenRepositoryMock) FindByIDCalls() []struct {
	Ctx      context.Context
	ID       uint
	Preloads []pkgrepository.Association
} {
	var calls []struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindByPreviousToken calls FindByPreviousTokenFunc.
func (mock *RefreshTokenRepositoryMock) FindByPreviousToken(ctx context.Context, token string) (*models.RefreshToken, error) {
	if mock.FindByPreviousTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.FindByPreviousTokenFunc: method is nil but RefreshTokenRepository.FindByPreviousToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockFindByPreviousToken.Lock()
	mock.calls.FindByPreviousToken = append(mock.calls.FindByPreviousToken, callInfo)
	mock.lockFindByPreviousToken.Unlock()
	return mock.FindByPreviousTokenFunc(ctx, token)
}

// FindByPreviousTokenCalls gets all the calls that were made to FindByPreviousToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.FindByPreviousTokenCalls())
func (mock *RefreshTokenRepositoryMock) FindByPreviousTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockFindByPreviousToken.RLock()
	calls = mock.calls.FindByPreviousToken
	mock.lockFindByPreviousToken.RUnlock()
	return calls
}

// FindByToken calls FindByTokenFunc.
func (mock *RefreshTokenRepositoryMock) FindByToken(ctx context.Context, token string) (*models.RefreshToken, error) {
	if mock.FindByTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.FindByTokenFunc: method is nil but RefreshTokenRepository.FindByToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockFindByToken.Lock()
	mock.calls.FindByToken = append(mock.calls.FindByToken, callInfo)
	mock.lockFindByToken.Unlock()
	return mock.FindByTokenFunc(ctx, token)
}

// FindByTokenCalls gets all the calls that were made to FindByToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.FindByTokenCalls())
func (mock *RefreshTokenRepositoryMock) FindByTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockFindByToken.RLock()
	calls = mock.calls.FindByToken
	mock.lockFindByToken.RUnlock()
	return calls
}

// GetValidCountByUserID calls GetValidCountByUserIDFunc.
func (mock *RefreshTokenRepositoryMock) GetValidCountByUserID(ctx context.Context, userID uint) (int64, error) {
	if mock.GetValidCountByUserIDFunc == nil {
		panic("RefreshTokenRepositoryMock.GetValidCountByUserIDFunc: method is nil but RefreshTokenRepository.GetValidCountByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetValidCountByUserID.Lock()
	mock.calls.GetValidCountByUserID = append(mock.calls.GetValidCountByUserID, callInfo)
	mock.lockGetValidCountByUserID.Unlock()
	return mock.GetValidCountByUserIDFunc(ctx, userID)
}

// GetValidCountByUserIDCalls gets all the calls that were made to GetValidCountByUserID.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.GetValidCountByUserIDCalls())
func (mock *RefreshTokenRepositoryMock) GetValidCountByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uint
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
	}
	mock.lockGetValidCountByUserID.RLock()
	calls = mock.calls.GetValidCountByUserID
	mock.lockGetValidCountByUserID.RUnlock()
	return calls
}

// RevokeAllByUserID calls RevokeAllByUserIDFunc.
func (mock *RefreshTokenRepositoryMock) RevokeAllByUserID(ctx context.Context, userID uint) error {
	if mock.RevokeAllByUserIDFunc == nil {
		panic("RefreshTokenRepositoryMock.RevokeAllByUserIDFunc: method is nil but RefreshTokenRepository.RevokeAllByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockRevokeAllByUserID.Lock()
	mock.calls.RevokeAllByUserID = append(mock.calls.RevokeAllByUserID, callInfo)
	mock.lockRevokeAllByUserID.Unlock()
	return mock.RevokeAllByUserIDFunc(ctx, userID)
}

// RevokeAllByUserIDCalls gets all the calls that were made to RevokeAllByUserID.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.RevokeAllByUserIDCalls())
func (mock *RefreshTokenRepositoryMock) RevokeAllByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uint
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
	}
	mock.lockRevokeAllByUserID.RLock()
	calls = mock.calls.RevokeAllByUserID
	mock.lockRevokeAllByUserID.RUnlock()
	return calls
}

// RevokeAllByUserIDExcept calls RevokeAllByUserIDExceptFunc.
func (mock *RefreshTokenRepositoryMock) RevokeAllByUserIDExcept(ctx context.Context, userID uint, exceptToken string) error {
	if mock.RevokeAllByUserIDExceptFunc == nil {
		panic("RefreshTokenRepositoryMock.RevokeAllByUserIDExceptFunc: method is nil but RefreshTokenRepository.RevokeAllByUserIDExcept was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UserID      uint
		ExceptToken string
	}{
		Ctx:         ctx,
		UserID:      userID,
		ExceptToken: exceptToken,
	}
	mock.lockRevokeAllByUserIDExcept.Lock()
	mock.calls.RevokeAllByUserIDExcept = append(mock.calls.RevokeAllByUserIDExcept, callInfo)
	mock.lockRevokeAllByUserIDExcept.Unlock()
	return mock.RevokeAllByUserIDExceptFunc(ctx, userID, exceptToken)
}

// RevokeAllByUserIDExceptCalls gets all the calls that were made to RevokeAllByUserIDExcept.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.RevokeAllByUserIDExceptCalls())
func (mock *RefreshTokenRepositoryMock) RevokeAllByUserIDExceptCalls() []struct {
	Ctx         context.Context
	UserID      uint
	ExceptToken string
} {
	var calls []struct {
		Ctx         context.Context
		UserID      uint
		ExceptToken string
	}
	mock.lockRevokeAllByUserIDExcept.RLock()
	calls = mock.calls.RevokeAllByUserIDExcept
	mock.lockRevokeAllByUserIDExcept.RUnlock()
	return calls
}

// RevokeByToken calls RevokeByTokenFunc.
func (mock *RefreshTokenRepositoryMock) RevokeByToken(ctx context.Context, token string) error {
	if mock.RevokeByTokenFunc == nil {
		panic("RefreshTokenRepositoryMock.RevokeByTokenFunc: method is nil but RefreshTokenRepository.RevokeByToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockRevokeByToken.Lock()
	mock.calls.RevokeByToken = append(mock.calls.RevokeByToken, callInfo)
	mock.lockRevokeByToken.Unlock()
	return mock.RevokeByTokenFunc(ctx, token)
}

// RevokeByTokenCalls gets all the calls that were made to RevokeByToken.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.RevokeByTokenCalls())
func (mock *RefreshTokenRepositoryMock) RevokeByTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockRevokeByToken.RLock()
	calls = mock.calls.RevokeByToken
	mock.lockRevokeByToken.RUnlock()
	return calls
}

// RevokeByTokenIfActive calls RevokeByTokenIfActiveFunc.
func (mock *RefreshTokenRepositoryMock) RevokeByTokenIfActive(ctx context.Context, token string) (bool, error) {
	if mock.RevokeByTokenIfActiveFunc == nil {
		panic("RefreshTokenRepositoryMock.RevokeByTokenIfActiveFunc: method is nil but RefreshTokenRepository.RevokeByTokenIfActive was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockRevokeByTokenIfActive.Lock()
	mock.calls.RevokeByTokenIfActive = append(mock.calls.RevokeByTokenIfActive, callInfo)
	mock.lockRevokeByTokenIfActive.Unlock()
	return mock.RevokeByTokenIfActiveFunc(ctx, token)
}

// RevokeByTokenIfActiveCalls gets all the calls that were made to RevokeByTokenIfActive.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.RevokeByTokenIfActiveCalls())
func (mock *RefreshTokenRepositoryMock) RevokeByTokenIfActiveCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockRevokeByTokenIfActive.RLock()
	calls = mock.calls.RevokeByTokenIfActive
	mock.lockRevokeByTokenIfActive.RUnlock()
	return calls
}

// RevokeOldestActiveByUserID calls RevokeOldestActiveByUserIDFunc.
func (mock *RefreshTokenRepositoryMock) RevokeOldestActiveByUserID(ctx context.Context, userID uint, n int) error {
	if mock.RevokeOldestActiveByUserIDFunc == nil {
		panic("RefreshTokenRepositoryMock.RevokeOldestActiveByUserIDFunc: method is nil but RefreshTokenRepository.RevokeOldestActiveByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
		N      int
	}{
		Ctx:    ctx,
		UserID: userID,
		N:      n,
	}
	mock.lockRevokeOldestActiveByUserID.Lock()
	mock.calls.RevokeOldestActiveByUserID = append(mock.calls.RevokeOldestActiveByUserID, callInfo)
	mock.lockRevokeOldestActiveByUserID.Unlock()
	return mock.RevokeOldestActiveByUserIDFunc(ctx, userID, n)
}

// RevokeOldestActiveByUserIDCalls gets all the calls that were made to RevokeOldestActiveByUserID.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.RevokeOldestActiveByUserIDCalls())
func (mock *RefreshTokenRepositoryMock) RevokeOldestActiveByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uint
	N      int
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
		N      int
	}
	mock.lockRevokeOldestActiveByUserID.RLock()
	calls = mock.calls.RevokeOldestActiveByUserID
	mock.lockRevokeOldestActiveByUserID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RefreshTokenRepositoryMock) Update(ctx context.Context, entity *models.RefreshToken) error {
	if mock.UpdateFunc == nil {
		panic("RefreshTokenRepositoryMock.UpdateFunc: method is nil but RefreshTokenRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.RefreshToken
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, entity)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.UpdateCalls())
func (mock *RefreshTokenRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Entity *models.RefreshToken
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.RefreshToken
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateTokenHashIfActive calls UpdateTokenHashIfActiveFunc.
func (mock *RefreshTokenRepositoryMock) UpdateTokenHashIfActive(ctx context.Context, oldToken string, newToken string) (bool, error) {
	if mock.UpdateTokenHashIfActiveFunc == nil {
		panic("RefreshTokenRepositoryMock.UpdateTokenHashIfActiveFunc: method is nil but RefreshTokenRepository.UpdateTokenHashIfActive was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		OldToken string
		NewToken string
	}{
		Ctx:      ctx,
		OldToken: oldToken,
		NewToken: newToken,
	}
	mock.lockUpdateTokenHashIfActive.Lock()
	mock.calls.UpdateTokenHashIfActive = append(mock.calls.UpdateTokenHashIfActive, callInfo)
	mock.lockUpdateTokenHashIfActive.Unlock()
	return mock.UpdateTokenHashIfActiveFunc(ctx, oldToken, newToken)
}

// UpdateTokenHashIfActiveCalls gets all the calls that were made to UpdateTokenHashIfActive.
// Check the length with:
//
//	len(mockedRefreshTokenRepository.UpdateTokenHashIfActiveCalls())
func (mock *RefreshTokenRepositoryMock) UpdateTokenHashIfActiveCalls() []struct {
	Ctx      context.Context
	OldToken string
	NewToken string
} {
	var calls []struct {
		Ctx      context.Context
		OldToken string
		NewToken string
	}
	mock.lockUpdateTokenHashIfActive.RLock()
	calls = mock.calls.UpdateTokenHashIfActive
	mock.lockUpdateTokenHashIfActive.RUnlock()
	return calls
}
