package repository

import (
	"context"
	"errors"
	"fmt"
	"time"

	cerrors "github.com/PhantomX7/athleton/pkg/errors"
	"github.com/PhantomX7/athleton/pkg/logger"
	"github.com/PhantomX7/athleton/pkg/pagination"
	"github.com/PhantomX7/athleton/pkg/utils"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Association is anything that can name itself for Preload. Both
// field.Struct[T] and field.Slice[T] generated by the GORM CLI satisfy it via
// their Name() method, so callers write `generated.User.AdminRole` instead of
// the stringly-typed "AdminRole" and typos become compile errors.
type Association interface {
	Name() string
}

// Preload wraps a literal association name for the rare cases where the name
// is decided at runtime (reflection, config-driven scopes) or the model
// predates the generator. Prefer passing a generated helper directly.
func Preload(name string) Association { return rawAssoc(name) }

type rawAssoc string

func (r rawAssoc) Name() string { return string(r) }

type IRepository[T any] interface {
	Create(ctx context.Context, entity *T) error
	Update(ctx context.Context, entity *T) error
	Delete(ctx context.Context, entity *T) error
	FindById(ctx context.Context, id uint, preloads ...Association) (*T, error)
	FindAll(ctx context.Context, pg *pagination.Pagination) ([]*T, error)
	Count(ctx context.Context, pg *pagination.Pagination) (int64, error)
}

type Repository[T any] struct {
	DB *gorm.DB
}

// GetDB returns the transaction-scoped *gorm.DB when the context carries one
// (placed there by libs/transaction_manager), otherwise the default handle.
func (r *Repository[T]) GetDB(ctx context.Context) *gorm.DB {
	if tx := utils.GetTxFromContext(ctx); tx != nil {
		return tx
	}
	return r.DB
}

// getEntityType returns the underlying T type name for log/error messages.
func (r *Repository[T]) getEntityType() string {
	return fmt.Sprintf("%T", *new(T))
}

// ---------------------------------------------------------------------------
// Implementation notes
//
// We use GORM's generics API (gorm.G[T]) for Create and FindById where it's
// cleaner and type-safer. The remaining methods stay on the classic API:
//
//   - Update: gorm.G[T] has no Save — it offers Create (insert) and Updates
//     (partial / selected fields), but neither gives you the "upsert by
//     primary key, write every column" semantics that callers rely on today
//     (read → mutate → persist). db.Save(entity) gets there in one call by
//     reflecting over the struct's schema-declared PK.
//   - Delete: gorm.G[T].Delete(ctx) requires an explicit Where; the classic
//     db.Delete(entity) reads the PK from the entity via schema reflection.
//   - FindAll / Count: the pagination package builds its filters and
//     limit/offset/order via classic-style scopes that take *gorm.DB. A naive
//     bridge — "pre-apply pagination to *gorm.DB, then wrap with gorm.G[T]"
//     — does NOT work: gorm.G[T]'s internal apply() opens a Session with
//     NewDB: true, which discards the clauses. The correct integration would
//     be to rewrite every pagination scope as a func(*gorm.Statement), a
//     much bigger refactor for no material gain. Classic Scopes(pg.Apply)
//     already works and is well exercised.
//
// ---------------------------------------------------------------------------

// Create inserts a new row for entity.
func (r *Repository[T]) Create(ctx context.Context, entity *T) error {
	start := time.Now()
	err := gorm.G[T](r.GetDB(ctx)).Create(ctx, entity)

	r.LogSlowQuery(ctx, "Create", time.Since(start), 500*time.Millisecond)

	if err != nil {
		return cerrors.NewInternalServerError(
			fmt.Sprintf("failed to create %s record", r.getEntityType()), err,
		)
	}
	return nil
}

// Update persists every field of entity using its primary key. We stay on the
// classic Save here — see the note at the top of this file.
func (r *Repository[T]) Update(ctx context.Context, entity *T) error {
	start := time.Now()
	err := r.GetDB(ctx).WithContext(ctx).Save(entity).Error

	r.LogSlowQuery(ctx, "Update", time.Since(start), 500*time.Millisecond)

	if err != nil {
		return cerrors.NewInternalServerError(
			fmt.Sprintf("failed to update %s record", r.getEntityType()), err,
		)
	}
	return nil
}

// Delete removes entity by its primary key. Classic API — see note above.
func (r *Repository[T]) Delete(ctx context.Context, entity *T) error {
	start := time.Now()
	err := r.GetDB(ctx).WithContext(ctx).Delete(entity).Error

	r.LogSlowQuery(ctx, "Delete", time.Since(start), 500*time.Millisecond)

	if err != nil {
		return cerrors.NewInternalServerError(
			fmt.Sprintf("failed to delete %s record", r.getEntityType()), err,
		)
	}
	return nil
}

// FindById returns the row with the given id, optionally preloading
// associations. Pass generated field helpers like generated.User.AdminRole;
// use repository.Preload("Name") only when the name must be dynamic.
func (r *Repository[T]) FindById(ctx context.Context, id uint, preloads ...Association) (*T, error) {
	start := time.Now()

	q := gorm.G[T](r.GetDB(ctx)).Where("id = ?", id)
	for _, p := range preloads {
		q = q.Preload(p.Name(), nil)
	}
	entity, err := q.First(ctx)

	r.LogSlowQuery(ctx, "FindById", time.Since(start), 500*time.Millisecond)

	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return &entity, cerrors.NewNotFoundError(
				fmt.Sprintf("%s record with id %v not found", r.getEntityType(), id),
			)
		}
		return &entity, cerrors.NewInternalServerError(
			fmt.Sprintf("failed to find %s record by id %v", r.getEntityType(), id), err,
		)
	}
	return &entity, nil
}

// FindAll runs the configured pagination (filters, order, limit, offset) and
// returns the results. Classic Scopes(pg.Apply) — see the note above.
func (r *Repository[T]) FindAll(ctx context.Context, pg *pagination.Pagination) ([]*T, error) {
	entities := make([]*T, 0)
	start := time.Now()

	err := r.GetDB(ctx).WithContext(ctx).
		Scopes(pg.Apply).
		Find(&entities).Error

	r.LogSlowQuery(ctx, "FindAll", time.Since(start), 1*time.Second)

	if err != nil {
		return nil, cerrors.NewInternalServerError(
			fmt.Sprintf("failed to find %s records", r.getEntityType()), err,
		)
	}
	return entities, nil
}

// Count returns the total row count after the filter portion of pagination.
// Classic Scopes(pg.ApplyWithoutMeta) — see the note above.
func (r *Repository[T]) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	var count int64
	start := time.Now()

	err := r.GetDB(ctx).WithContext(ctx).
		Scopes(pg.ApplyWithoutMeta).
		Model(new(T)).Count(&count).Error

	r.LogSlowQuery(ctx, "Count", time.Since(start), 1*time.Second)

	if err != nil {
		return 0, cerrors.NewInternalServerError(
			fmt.Sprintf("failed to count %s records", r.getEntityType()), err,
		)
	}
	return count, nil
}

// LogSlowQuery emits a warning when a single call exceeds threshold.
func (r *Repository[T]) LogSlowQuery(ctx context.Context, operation string, duration, threshold time.Duration) {
	if duration > threshold {
		logger.Warn("Slow query detected",
			zap.String("request_id", utils.GetRequestIDFromContext(ctx)),
			zap.String("entity_type", r.getEntityType()),
			zap.String("operation", operation),
			zap.Duration("duration", duration),
			zap.Duration("threshold", threshold),
		)
	}
}
