// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/models"
	configrepository "github.com/PhantomX7/athleton/internal/modules/config/repository"
	"github.com/PhantomX7/athleton/pkg/pagination"
	pkgrepository "github.com/PhantomX7/athleton/pkg/repository"
)

// Ensure, that ConfigRepositoryMock does implement configrepository.ConfigRepository.
// If this is not the case, regenerate this file with moq.
var _ configrepository.ConfigRepository = &ConfigRepositoryMock{}

// ConfigRepositoryMock is a mock implementation of configrepository.ConfigRepository.
//
//	func TestSomethingThatUsesConfigRepository(t *testing.T) {
//
//		// make and configure a mocked configrepository.ConfigRepository
//		mockedConfigRepository := &ConfigRepositoryMock{
//			CountFunc: func(ctx context.Context, pg *pagination.Pagination) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CountPublicFunc: func(ctx context.Context, pg *pagination.Pagination) (int64, error) {
//				panic("mock out the CountPublic method")
//			},
//			CreateFunc: func(ctx context.Context, entity *models.Config) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, entity *models.Config) error {
//				panic("mock out the Delete method")
//			},
//			FindAllFunc: func(ctx context.Context, pg *pagination.Pagination) ([]*models.Config, error) {
//				panic("mock out the FindAll method")
//			},
//			FindAllPublicFunc: func(ctx context.Context, pg *pagination.Pagination) ([]*models.Config, error) {
//				panic("mock out the FindAllPublic method")
//			},
//			FindByIDFunc: func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.Config, error) {
//				panic("mock out the FindByID method")
//			},
//			FindByKeyFunc: func(ctx context.Context, key string) (*models.Config, error) {
//				panic("mock out the FindByKey method")
//			},
//			FindPublicByKeyFunc: func(ctx context.Context, key string) (*models.Config, error) {
//				panic("mock out the FindPublicByKey method")
//			},
//			UpdateFunc: func(ctx context.Context, entity *models.Config) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedConfigRepository in code that requires configrepository.ConfigRepository
//		// and then make assertions.
//
//	}
type ConfigRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, pg *pagination.Pagination) (int64, error)

	// CountPublicFunc mocks the CountPublic method.
	CountPublicFunc func(ctx context.Context, pg *pagination.Pagination) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *models.Config) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, entity *models.Config) error

	// FindAllFunc mocks the FindAll method.
	FindAllFunc func(ctx context.Context, pg *pagination.Pagination) ([]*models.Config, error)

	// FindAllPublicFunc mocks the FindAllPublic method.
	FindAllPublicFunc func(ctx context.Context, pg *pagination.Pagination) ([]*models.Config, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.Config, error)

	// FindByKeyFunc mocks the FindByKey method.
	FindByKeyFunc func(ctx context.Context, key string) (*models.Config, error)

	// FindPublicByKeyFunc mocks the FindPublicByKey method.
	FindPublicByKeyFunc func(ctx context.Context, key string) (*models.Config, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, entity *models.Config) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// CountPublic holds details about calls to the CountPublic method.
		CountPublic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.Config
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.Config
		}
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// FindAllPublic holds details about calls to the FindAllPublic method.
		FindAllPublic []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
			// Preloads is the preloads argument value.
			Preloads []pkgrepository.Association
		}
		// FindByKey holds details about calls to the FindByKey method.
		FindByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// FindPublicByKey holds details about calls to the FindPublicByKey method.
		FindPublicByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.Config
		}
	}
	lockCount           sync.RWMutex
	lockCountPublic     sync.RWMutex
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockFindAll         sync.RWMutex
	lockFindAllPublic   sync.RWMutex
	lockFindByID        sync.RWMutex
	lockFindByKey       sync.RWMutex
	lockFindPublicByKey sync.RWMutex
	lockUpdate          sync.RWMutex
}

// Count calls CountFunc.
func (mock *ConfigRepositoryMock) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	if mock.CountFunc == nil {
		panic("ConfigRepositoryMock.CountFunc: method is nil but ConfigRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, pg)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedConfigRepository.CountCalls())
func (mock *ConfigRepositoryMock) CountCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// CountPublic calls CountPublicFunc.
func (mock *ConfigRepositoryMock) CountPublic(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	if mock.CountPublicFunc == nil {
		panic("ConfigRepositoryMock.CountPublicFunc: method is nil but ConfigRepository.CountPublic was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockCountPublic.Lock()
	mock.calls.CountPublic = append(mock.calls.CountPublic, callInfo)
	mock.lockCountPublic.Unlock()
	return mock.CountPublicFunc(ctx, pg)
}

// CountPublicCalls gets all the calls that were made to CountPublic.
// Check the length with:
//
//	len(mockedConfigRepository.CountPublicCalls())
func (mock *ConfigRepositoryMock) CountPublicCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockCountPublic.RLock()
	calls = mock.calls.CountPublic
	mock.lockCountPublic.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ConfigRepositoryMock) Create(ctx context.Context, entity *models.Config) error {
	if mock.CreateFunc == nil {
		panic("ConfigRepositoryMock.CreateFunc: method is nil but ConfigRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.Config
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedConfigRepository.CreateCalls())
func (mock *ConfigRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *models.Config
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.Config
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ConfigRepositoryMock) Delete(ctx context.Context, entity *models.Config) error {
	if mock.DeleteFunc == nil {
		panic("ConfigRepositoryMock.DeleteFunc: method is nil but ConfigRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.Config
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, entity)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedConfigRepository.DeleteCalls())
func (mock *ConfigRepositoryMock) DeleteCalls() []struct {
	Ctx    context.Context
	Entity *models.Config
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.Config
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindAll calls FindAllFunc.
func (mock *ConfigRepositoryMock) FindAll(ctx context.Context, pg *pagination.Pagination) ([]*models.Config, error) {
	if mock.FindAllFunc == nil {
		panic("ConfigRepositoryMock.FindAllFunc: method is nil but ConfigRepository.FindAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	mock.lockFindAll.Unlock()
	return mock.FindAllFunc(ctx, pg)
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//
//	len(mockedConfigRepository.FindAllCalls())
func (mock *ConfigRepositoryMock) FindAllCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockFindAll.RLock()
	calls = mock.calls.FindAll
	mock.lockFindAll.RUnlock()
	return calls
}

// FindAllPublic calls FindAllPublicFunc.
func (mock *ConfigRepositoryMock) FindAllPublic(ctx context.Context, pg *pagination.Pagination) ([]*models.Config, error) {
	if mock.FindAllPublicFunc == nil {
		panic("ConfigRepositoryMock.FindAllPublicFunc: method is nil but ConfigRepository.FindAllPublic was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockFindAllPublic.Lock()
	mock.calls.FindAllPublic = append(mock.calls.FindAllPublic, callInfo)
	mock.lockFindAllPublic.Unlock()
	return mock.FindAllPublicFunc(ctx, pg)
}

// FindAllPublicCalls gets all the calls that were made to FindAllPublic.
// Check the length with:
//
//	len(mockedConfigRepository.FindAllPublicCalls())
func (mock *ConfigRepositoryMock) FindAllPublicCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockFindAllPublic.RLock()
	calls = mock.calls.FindAllPublic
	mock.lockFindAllPublic.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *ConfigRepositoryMock) FindByID(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.Config, error) {
	if mock.FindByIDFunc == nil {
		panic("ConfigRepositoryMock.FindByIDFunc: method is nil but ConfigRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}{
		Ctx:      ctx,
		ID:       id,
		Preloads: preloads,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id, preloads...)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedConfigRepository.FindByIDCalls())
func (mock *ConfigRepositoryMock) FindByIDCalls() []struct {
	Ctx      context.Context
	ID       uint
	Preloads []pkgrepository.Association
} {
	var calls []struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindByKey calls FindByKeyFunc.
func (mock *ConfigRepositoryMock) FindByKey(ctx context.Context, key string) (*models.Config, error) {
	if mock.FindByKeyFunc == nil {
		panic("ConfigRepositoryMock.FindByKeyFunc: method is nil but ConfigRepository.FindByKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockFindByKey.Lock()
	mock.calls.FindByKey = append(mock.calls.FindByKey, callInfo)
	mock.lockFindByKey.Unlock()
	return mock.FindByKeyFunc(ctx, key)
}

// FindByKeyCalls gets all the calls that were made to FindByKey.
// Check the length with:
//
//	len(mockedConfigRepository.FindByKeyCalls())
func (mock *ConfigRepositoryMock) FindByKeyCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockFindByKey.RLock()
	calls = mock.calls.FindByKey
	mock.lockFindByKey.RUnlock()
	return calls
}

// FindPublicByKey calls FindPublicByKeyFunc.
func (mock *ConfigRepositoryMock) FindPublicByKey(ctx context.Context, key string) (*models.Config, error) {
	if mock.FindPublicByKeyFunc == nil {
		panic("ConfigRepositoryMock.FindPublicByKeyFunc: method is nil but ConfigRepository.FindPublicByKey was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockFindPublicByKey.Lock()
	mock.calls.FindPublicByKey = append(mock.calls.FindPublicByKey, callInfo)
	mock.lockFindPublicByKey.Unlock()
	return mock.FindPublicByKeyFunc(ctx, key)
}

// FindPublicByKeyCalls gets all the calls that were made to FindPublicByKey.
// Check the length with:
//
//	len(mockedConfigRepository.FindPublicByKeyCalls())
func (mock *ConfigRepositoryMock) FindPublicByKeyCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockFindPublicByKey.RLock()
	calls = mock.calls.FindPublicByKey
	mock.lockFindPublicByKey.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ConfigRepositoryMock) Update(ctx context.Context, entity *models.Config) error {
	if mock.UpdateFunc == nil {
		panic("ConfigRepositoryMock.UpdateFunc: method is nil but ConfigRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.Config
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, entity)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedConfigRepository.UpdateCalls())
func (mock *ConfigRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Entity *models.Config
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.Config
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
