// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	libscasbin "github.com/PhantomX7/athleton/libs/casbin"
	v3 "github.com/casbin/casbin/v3"
)

// Ensure, that ClientMock does implement libscasbin.Client.
// If this is not the case, regenerate this file with moq.
var _ libscasbin.Client = &ClientMock{}

// ClientMock is a mock implementation of libscasbin.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked libscasbin.Client
//		mockedClient := &ClientMock{
//			AddRolePermissionsFunc: func(roleID uint, permissions []string) error {
//				panic("mock out the AddRolePermissions method")
//			},
//			CheckPermissionFunc: func(roleID uint, permission string) (bool, error) {
//				panic("mock out the CheckPermission method")
//			},
//			CheckPermissionWithRootFunc: func(userRole string, adminRoleID *uint, permission string) (bool, error) {
//				panic("mock out the CheckPermissionWithRoot method")
//			},
//			DeleteRoleFunc: func(roleID uint) error {
//				panic("mock out the DeleteRole method")
//			},
//			GetEnforcerFunc: func() *v3.Enforcer {
//				panic("mock out the GetEnforcer method")
//			},
//			GetRolePermissionsFunc: func(roleID uint) []string {
//				panic("mock out the GetRolePermissions method")
//			},
//			RemoveRolePermissionsFunc: func(roleID uint, permissions []string) error {
//				panic("mock out the RemoveRolePermissions method")
//			},
//			SetRolePermissionsFunc: func(roleID uint, permissions []string) error {
//				panic("mock out the SetRolePermissions method")
//			},
//		}
//
//		// use mockedClient in code that requires libscasbin.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// AddRolePermissionsFunc mocks the AddRolePermissions method.
	AddRolePermissionsFunc func(roleID uint, permissions []string) error

	// CheckPermissionFunc mocks the CheckPermission method.
	CheckPermissionFunc func(roleID uint, permission string) (bool, error)

	// CheckPermissionWithRootFunc mocks the CheckPermissionWithRoot method.
	CheckPermissionWithRootFunc func(userRole string, adminRoleID *uint, permission string) (bool, error)

	// DeleteRoleFunc mocks the DeleteRole method.
	DeleteRoleFunc func(roleID uint) error

	// GetEnforcerFunc mocks the GetEnforcer method.
	GetEnforcerFunc func() *v3.Enforcer

	// GetRolePermissionsFunc mocks the GetRolePermissions method.
	GetRolePermissionsFunc func(roleID uint) []string

	// RemoveRolePermissionsFunc mocks the RemoveRolePermissions method.
	RemoveRolePermissionsFunc func(roleID uint, permissions []string) error

	// SetRolePermissionsFunc mocks the SetRolePermissions method.
	SetRolePermissionsFunc func(roleID uint, permissions []string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddRolePermissions holds details about calls to the AddRolePermissions method.
		AddRolePermissions []struct {
			// RoleID is the roleID argument value.
			RoleID uint
			// Permissions is the permissions argument value.
			Permissions []string
		}
		// CheckPermission holds details about calls to the CheckPermission method.
		CheckPermission []struct {
			// RoleID is the roleID argument value.
			RoleID uint
			// Permission is the permission argument value.
			Permission string
		}
		// CheckPermissionWithRoot holds details about calls to the CheckPermissionWithRoot method.
		CheckPermissionWithRoot []struct {
			// UserRole is the userRole argument value.
			UserRole string
			// AdminRoleID is the adminRoleID argument value.
			AdminRoleID *uint
			// Permission is the permission argument value.
			Permission string
		}
		// DeleteRole holds details about calls to the DeleteRole method.
		DeleteRole []struct {
			// RoleID is the roleID argument value.
			RoleID uint
		}
		// GetEnforcer holds details about calls to the GetEnforcer method.
		GetEnforcer []struct {
		}
		// GetRolePermissions holds details about calls to the GetRolePermissions method.
		GetRolePermissions []struct {
			// RoleID is the roleID argument value.
			RoleID uint
		}
		// RemoveRolePermissions holds details about calls to the RemoveRolePermissions method.
		RemoveRolePermissions []struct {
			// RoleID is the roleID argument value.
			RoleID uint
			// Permissions is the permissions argument value.
			Permissions []string
		}
		// SetRolePermissions holds details about calls to the SetRolePermissions method.
		SetRolePermissions []struct {
			// RoleID is the roleID argument value.
			RoleID uint
			// Permissions is the permissions argument value.
			Permissions []string
		}
	}
	lockAddRolePermissions      sync.RWMutex
	lockCheckPermission         sync.RWMutex
	lockCheckPermissionWithRoot sync.RWMutex
	lockDeleteRole              sync.RWMutex
	lockGetEnforcer             sync.RWMutex
	lockGetRolePermissions      sync.RWMutex
	lockRemoveRolePermissions   sync.RWMutex
	lockSetRolePermissions      sync.RWMutex
}

// AddRolePermissions calls AddRolePermissionsFunc.
func (mock *ClientMock) AddRolePermissions(roleID uint, permissions []string) error {
	if mock.AddRolePermissionsFunc == nil {
		panic("ClientMock.AddRolePermissionsFunc: method is nil but Client.AddRolePermissions was just called")
	}
	callInfo := struct {
		RoleID      uint
		Permissions []string
	}{
		RoleID:      roleID,
		Permissions: permissions,
	}
	mock.lockAddRolePermissions.Lock()
	mock.calls.AddRolePermissions = append(mock.calls.AddRolePermissions, callInfo)
	mock.lockAddRolePermissions.Unlock()
	return mock.AddRolePermissionsFunc(roleID, permissions)
}

// AddRolePermissionsCalls gets all the calls that were made to AddRolePermissions.
// Check the length with:
//
//	len(mockedClient.AddRolePermissionsCalls())
func (mock *ClientMock) AddRolePermissionsCalls() []struct {
	RoleID      uint
	Permissions []string
} {
	var calls []struct {
		RoleID      uint
		Permissions []string
	}
	mock.lockAddRolePermissions.RLock()
	calls = mock.calls.AddRolePermissions
	mock.lockAddRolePermissions.RUnlock()
	return calls
}

// CheckPermission calls CheckPermissionFunc.
func (mock *ClientMock) CheckPermission(roleID uint, permission string) (bool, error) {
	if mock.CheckPermissionFunc == nil {
		panic("ClientMock.CheckPermissionFunc: method is nil but Client.CheckPermission was just called")
	}
	callInfo := struct {
		RoleID     uint
		Permission string
	}{
		RoleID:     roleID,
		Permission: permission,
	}
	mock.lockCheckPermission.Lock()
	mock.calls.CheckPermission = append(mock.calls.CheckPermission, callInfo)
	mock.lockCheckPermission.Unlock()
	return mock.CheckPermissionFunc(roleID, permission)
}

// CheckPermissionCalls gets all the calls that were made to CheckPermission.
// Check the length with:
//
//	len(mockedClient.CheckPermissionCalls())
func (mock *ClientMock) CheckPermissionCalls() []struct {
	RoleID     uint
	Permission string
} {
	var calls []struct {
		RoleID     uint
		Permission string
	}
	mock.lockCheckPermission.RLock()
	calls = mock.calls.CheckPermission
	mock.lockCheckPermission.RUnlock()
	return calls
}

// CheckPermissionWithRoot calls CheckPermissionWithRootFunc.
func (mock *ClientMock) CheckPermissionWithRoot(userRole string, adminRoleID *uint, permission string) (bool, error) {
	if mock.CheckPermissionWithRootFunc == nil {
		panic("ClientMock.CheckPermissionWithRootFunc: method is nil but Client.CheckPermissionWithRoot was just called")
	}
	callInfo := struct {
		UserRole    string
		AdminRoleID *uint
		Permission  string
	}{
		UserRole:    userRole,
		AdminRoleID: adminRoleID,
		Permission:  permission,
	}
	mock.lockCheckPermissionWithRoot.Lock()
	mock.calls.CheckPermissionWithRoot = append(mock.calls.CheckPermissionWithRoot, callInfo)
	mock.lockCheckPermissionWithRoot.Unlock()
	return mock.CheckPermissionWithRootFunc(userRole, adminRoleID, permission)
}

// CheckPermissionWithRootCalls gets all the calls that were made to CheckPermissionWithRoot.
// Check the length with:
//
//	len(mockedClient.CheckPermissionWithRootCalls())
func (mock *ClientMock) CheckPermissionWithRootCalls() []struct {
	UserRole    string
	AdminRoleID *uint
	Permission  string
} {
	var calls []struct {
		UserRole    string
		AdminRoleID *uint
		Permission  string
	}
	mock.lockCheckPermissionWithRoot.RLock()
	calls = mock.calls.CheckPermissionWithRoot
	mock.lockCheckPermissionWithRoot.RUnlock()
	return calls
}

// DeleteRole calls DeleteRoleFunc.
func (mock *ClientMock) DeleteRole(roleID uint) error {
	if mock.DeleteRoleFunc == nil {
		panic("ClientMock.DeleteRoleFunc: method is nil but Client.DeleteRole was just called")
	}
	callInfo := struct {
		RoleID uint
	}{
		RoleID: roleID,
	}
	mock.lockDeleteRole.Lock()
	mock.calls.DeleteRole = append(mock.calls.DeleteRole, callInfo)
	mock.lockDeleteRole.Unlock()
	return mock.DeleteRoleFunc(roleID)
}

// DeleteRoleCalls gets all the calls that were made to DeleteRole.
// Check the length with:
//
//	len(mockedClient.DeleteRoleCalls())
func (mock *ClientMock) DeleteRoleCalls() []struct {
	RoleID uint
} {
	var calls []struct {
		RoleID uint
	}
	mock.lockDeleteRole.RLock()
	calls = mock.calls.DeleteRole
	mock.lockDeleteRole.RUnlock()
	return calls
}

// GetEnforcer calls GetEnforcerFunc.
func (mock *ClientMock) GetEnforcer() *v3.Enforcer {
	if mock.GetEnforcerFunc == nil {
		panic("ClientMock.GetEnforcerFunc: method is nil but Client.GetEnforcer was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetEnforcer.Lock()
	mock.calls.GetEnforcer = append(mock.calls.GetEnforcer, callInfo)
	mock.lockGetEnforcer.Unlock()
	return mock.GetEnforcerFunc()
}

// GetEnforcerCalls gets all the calls that were made to GetEnforcer.
// Check the length with:
//
//	len(mockedClient.GetEnforcerCalls())
func (mock *ClientMock) GetEnforcerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetEnforcer.RLock()
	calls = mock.calls.GetEnforcer
	mock.lockGetEnforcer.RUnlock()
	return calls
}

// GetRolePermissions calls GetRolePermissionsFunc.
func (mock *ClientMock) GetRolePermissions(roleID uint) []string {
	if mock.GetRolePermissionsFunc == nil {
		panic("ClientMock.GetRolePermissionsFunc: method is nil but Client.GetRolePermissions was just called")
	}
	callInfo := struct {
		RoleID uint
	}{
		RoleID: roleID,
	}
	mock.lockGetRolePermissions.Lock()
	mock.calls.GetRolePermissions = append(mock.calls.GetRolePermissions, callInfo)
	mock.lockGetRolePermissions.Unlock()
	return mock.GetRolePermissionsFunc(roleID)
}

// GetRolePermissionsCalls gets all the calls that were made to GetRolePermissions.
// Check the length with:
//
//	len(mockedClient.GetRolePermissionsCalls())
func (mock *ClientMock) GetRolePermissionsCalls() []struct {
	RoleID uint
} {
	var calls []struct {
		RoleID uint
	}
	mock.lockGetRolePermissions.RLock()
	calls = mock.calls.GetRolePermissions
	mock.lockGetRolePermissions.RUnlock()
	return calls
}

// RemoveRolePermissions calls RemoveRolePermissionsFunc.
func (mock *ClientMock) RemoveRolePermissions(roleID uint, permissions []string) error {
	if mock.RemoveRolePermissionsFunc == nil {
		panic("ClientMock.RemoveRolePermissionsFunc: method is nil but Client.RemoveRolePermissions was just called")
	}
	callInfo := struct {
		RoleID      uint
		Permissions []string
	}{
		RoleID:      roleID,
		Permissions: permissions,
	}
	mock.lockRemoveRolePermissions.Lock()
	mock.calls.RemoveRolePermissions = append(mock.calls.RemoveRolePermissions, callInfo)
	mock.lockRemoveRolePermissions.Unlock()
	return mock.RemoveRolePermissionsFunc(roleID, permissions)
}

// RemoveRolePermissionsCalls gets all the calls that were made to RemoveRolePermissions.
// Check the length with:
//
//	len(mockedClient.RemoveRolePermissionsCalls())
func (mock *ClientMock) RemoveRolePermissionsCalls() []struct {
	RoleID      uint
	Permissions []string
} {
	var calls []struct {
		RoleID      uint
		Permissions []string
	}
	mock.lockRemoveRolePermissions.RLock()
	calls = mock.calls.RemoveRolePermissions
	mock.lockRemoveRolePermissions.RUnlock()
	return calls
}

// SetRolePermissions calls SetRolePermissionsFunc.
func (mock *ClientMock) SetRolePermissions(roleID uint, permissions []string) error {
	if mock.SetRolePermissionsFunc == nil {
		panic("ClientMock.SetRolePermissionsFunc: method is nil but Client.SetRolePermissions was just called")
	}
	callInfo := struct {
		RoleID      uint
		Permissions []string
	}{
		RoleID:      roleID,
		Permissions: permissions,
	}
	mock.lockSetRolePermissions.Lock()
	mock.calls.SetRolePermissions = append(mock.calls.SetRolePermissions, callInfo)
	mock.lockSetRolePermissions.Unlock()
	return mock.SetRolePermissionsFunc(roleID, permissions)
}

// SetRolePermissionsCalls gets all the calls that were made to SetRolePermissions.
// Check the length with:
//
//	len(mockedClient.SetRolePermissionsCalls())
func (mock *ClientMock) SetRolePermissionsCalls() []struct {
	RoleID      uint
	Permissions []string
} {
	var calls []struct {
		RoleID      uint
		Permissions []string
	}
	mock.lockSetRolePermissions.RLock()
	calls = mock.calls.SetRolePermissions
	mock.lockSetRolePermissions.RUnlock()
	return calls
}
