// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/models"
	userrepository "github.com/PhantomX7/athleton/internal/modules/user/repository"
	"github.com/PhantomX7/athleton/pkg/pagination"
	pkgrepository "github.com/PhantomX7/athleton/pkg/repository"
)

// Ensure, that UserRepositoryMock does implement userrepository.UserRepository.
// If this is not the case, regenerate this file with moq.
var _ userrepository.UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of userrepository.UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked userrepository.UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			CountFunc: func(ctx context.Context, pg *pagination.Pagination) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, entity *models.User) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, entity *models.User) error {
//				panic("mock out the Delete method")
//			},
//			FindAllFunc: func(ctx context.Context, pg *pagination.Pagination) ([]*models.User, error) {
//				panic("mock out the FindAll method")
//			},
//			FindByEmailFunc: func(ctx context.Context, email string) (*models.User, error) {
//				panic("mock out the FindByEmail method")
//			},
//			FindByIDFunc: func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.User, error) {
//				panic("mock out the FindByID method")
//			},
//			FindByIDForUpdateFunc: func(ctx context.Context, id uint) (*models.User, error) {
//				panic("mock out the FindByIDForUpdate method")
//			},
//			FindByUsernameFunc: func(ctx context.Context, username string) (*models.User, error) {
//				panic("mock out the FindByUsername method")
//			},
//			UpdateFunc: func(ctx context.Context, entity *models.User) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires userrepository.UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, pg *pagination.Pagination) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *models.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, entity *models.User) error

	// FindAllFunc mocks the FindAll method.
	FindAllFunc func(ctx context.Context, pg *pagination.Pagination) ([]*models.User, error)

	// FindByEmailFunc mocks the FindByEmail method.
	FindByEmailFunc func(ctx context.Context, email string) (*models.User, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.User, error)

	// FindByIDForUpdateFunc mocks the FindByIDForUpdate method.
	FindByIDForUpdateFunc func(ctx context.Context, id uint) (*models.User, error)

	// FindByUsernameFunc mocks the FindByUsername method.
	FindByUsernameFunc func(ctx context.Context, username string) (*models.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, entity *models.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.User
		}
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// FindByEmail holds details about calls to the FindByEmail method.
		FindByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
			// Preloads is the preloads argument value.
			Preloads []pkgrepository.Association
		}
		// FindByIDForUpdate holds details about calls to the FindByIDForUpdate method.
		FindByIDForUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// FindByUsername holds details about calls to the FindByUsername method.
		FindByUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Username is the username argument value.
			Username string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.User
		}
	}
	lockCount             sync.RWMutex
	lockCreate            sync.RWMutex
	lockDelete            sync.RWMutex
	lockFindAll           sync.RWMutex
	lockFindByEmail       sync.RWMutex
	lockFindByID          sync.RWMutex
	lockFindByIDForUpdate sync.RWMutex
	lockFindByUsername    sync.RWMutex
	lockUpdate            sync.RWMutex
}

// Count calls CountFunc.
func (mock *UserRepositoryMock) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	if mock.CountFunc == nil {
		panic("UserRepositoryMock.CountFunc: method is nil but UserRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, pg)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedUserRepository.CountCalls())
func (mock *UserRepositoryMock) CountCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *UserRepositoryMock) Create(ctx context.Context, entity *models.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepositoryMock.CreateFunc: method is nil but UserRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.User
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepository.CreateCalls())
func (mock *UserRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *models.User
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryMock) Delete(ctx context.Context, entity *models.User) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryMock.DeleteFunc: method is nil but UserRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.User
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, entity)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepository.DeleteCalls())
func (mock *UserRepositoryMock) DeleteCalls() []struct {
	Ctx    context.Context
	Entity *models.User
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.User
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindAll calls FindAllFunc.
func (mock *UserRepositoryMock) FindAll(ctx context.Context, pg *pagination.Pagination) ([]*models.User, error) {
	if mock.FindAllFunc == nil {
		panic("UserRepositoryMock.FindAllFunc: method is nil but UserRepository.FindAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	mock.lockFindAll.Unlock()
	return mock.FindAllFunc(ctx, pg)
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//
//	len(mockedUserRepository.FindAllCalls())
func (mock *UserRepositoryMock) FindAllCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockFindAll.RLock()
	calls = mock.calls.FindAll
	mock.lockFindAll.RUnlock()
	return calls
}

// FindByEmail calls FindByEmailFunc.
func (mock *UserRepositoryMock) FindByEmail(ctx context.Context, email string) (*models.User, error) {
	if mock.FindByEmailFunc == nil {
		panic("UserRepositoryMock.FindByEmailFunc: method is nil but UserRepository.FindByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockFindByEmail.Lock()
	mock.calls.FindByEmail = append(mock.calls.FindByEmail, callInfo)
	mock.lockFindByEmail.Unlock()
	return mock.FindByEmailFunc(ctx, email)
}

// FindByEmailCalls gets all the calls that were made to FindByEmail.
// Check the length with:
//
//	len(mockedUserRepository.FindByEmailCalls())
func (mock *UserRepositoryMock) FindByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockFindByEmail.RLock()
	calls = mock.calls.FindByEmail
	mock.lockFindByEmail.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *UserRepositoryMock) FindByID(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.User, error) {
	if mock.FindByIDFunc == nil {
		panic("UserRepositoryMock.FindByIDFunc: method is nil but UserRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}{
		Ctx:      ctx,
		ID:       id,
		Preloads: preloads,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id, preloads...)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDCalls())
func (mock *UserRepositoryMock) FindByIDCalls() []struct {
	Ctx      context.Context
	ID       uint
	Preloads []pkgrepository.Association
} {
	var calls []struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindByIDForUpdate calls FindByIDForUpdateFunc.
func (mock *UserRepositoryMock) FindByIDForUpdate(ctx context.Context, id uint) (*models.User, error) {
	if mock.FindByIDForUpdateFunc == nil {
		panic("UserRepositoryMock.FindByIDForUpdateFunc: method is nil but UserRepository.FindByIDForUpdate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindByIDForUpdate.Lock()
	mock.calls.FindByIDForUpdate = append(mock.calls.FindByIDForUpdate, callInfo)
	mock.lockFindByIDForUpdate.Unlock()
	return mock.FindByIDForUpdateFunc(ctx, id)
}

// FindByIDForUpdateCalls gets all the calls that were made to FindByIDForUpdate.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDForUpdateCalls())
func (mock *UserRepositoryMock) FindByIDForUpdateCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockFindByIDForUpdate.RLock()
	calls = mock.calls.FindByIDForUpdate
	mock.lockFindByIDForUpdate.RUnlock()
	return calls
}

// FindByUsername calls FindByUsernameFunc.
func (mock *UserRepositoryMock) FindByUsername(ctx context.Context, username string) (*models.User, error) {
	if mock.FindByUsernameFunc == nil {
		panic("UserRepositoryMock.FindByUsernameFunc: method is nil but UserRepository.FindByUsername was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Username string
	}{
		Ctx:      ctx,
		Username: username,
	}
	mock.lockFindByUsername.Lock()
	mock.calls.FindByUsername = append(mock.calls.FindByUsername, callInfo)
	mock.lockFindByUsername.Unlock()
	return mock.FindByUsernameFunc(ctx, username)
}

// FindByUsernameCalls gets all the calls that were made to FindByUsername.
// Check the length with:
//
//	len(mockedUserRepository.FindByUsernameCalls())
func (mock *UserRepositoryMock) FindByUsernameCalls() []struct {
	Ctx      context.Context
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Username string
	}
	mock.lockFindByUsername.RLock()
	calls = mock.calls.FindByUsername
	mock.lockFindByUsername.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepositoryMock) Update(ctx context.Context, entity *models.User) error {
	if mock.UpdateFunc == nil {
		panic("UserRepositoryMock.UpdateFunc: method is nil but UserRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.User
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, entity)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepository.UpdateCalls())
func (mock *UserRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Entity *models.User
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
