// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/models"
	adminrolerepository "github.com/PhantomX7/athleton/internal/modules/admin_role/repository"
	"github.com/PhantomX7/athleton/pkg/pagination"
	pkgrepository "github.com/PhantomX7/athleton/pkg/repository"
)

// Ensure, that AdminRoleRepositoryMock does implement adminrolerepository.AdminRoleRepository.
// If this is not the case, regenerate this file with moq.
var _ adminrolerepository.AdminRoleRepository = &AdminRoleRepositoryMock{}

// AdminRoleRepositoryMock is a mock implementation of adminrolerepository.AdminRoleRepository.
//
//	func TestSomethingThatUsesAdminRoleRepository(t *testing.T) {
//
//		// make and configure a mocked adminrolerepository.AdminRoleRepository
//		mockedAdminRoleRepository := &AdminRoleRepositoryMock{
//			CountFunc: func(ctx context.Context, pg *pagination.Pagination) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CountUsersWithRoleFunc: func(ctx context.Context, roleID uint) (int64, error) {
//				panic("mock out the CountUsersWithRole method")
//			},
//			CreateFunc: func(ctx context.Context, entity *models.AdminRole) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, entity *models.AdminRole) error {
//				panic("mock out the Delete method")
//			},
//			FindAllFunc: func(ctx context.Context, pg *pagination.Pagination) ([]*models.AdminRole, error) {
//				panic("mock out the FindAll method")
//			},
//			FindByIDFunc: func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.AdminRole, error) {
//				panic("mock out the FindByID method")
//			},
//			FindByIDForUpdateFunc: func(ctx context.Context, id uint) (*models.AdminRole, error) {
//				panic("mock out the FindByIDForUpdate method")
//			},
//			FindByNameFunc: func(ctx context.Context, name string) (*models.AdminRole, error) {
//				panic("mock out the FindByName method")
//			},
//			UpdateFunc: func(ctx context.Context, entity *models.AdminRole) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedAdminRoleRepository in code that requires adminrolerepository.AdminRoleRepository
//		// and then make assertions.
//
//	}
type AdminRoleRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, pg *pagination.Pagination) (int64, error)

	// CountUsersWithRoleFunc mocks the CountUsersWithRole method.
	CountUsersWithRoleFunc func(ctx context.Context, roleID uint) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *models.AdminRole) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, entity *models.AdminRole) error

	// FindAllFunc mocks the FindAll method.
	FindAllFunc func(ctx context.Context, pg *pagination.Pagination) ([]*models.AdminRole, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.AdminRole, error)

	// FindByIDForUpdateFunc mocks the FindByIDForUpdate method.
	FindByIDForUpdateFunc func(ctx context.Context, id uint) (*models.AdminRole, error)

	// FindByNameFunc mocks the FindByName method.
	FindByNameFunc func(ctx context.Context, name string) (*models.AdminRole, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, entity *models.AdminRole) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// CountUsersWithRole holds details about calls to the CountUsersWithRole method.
		CountUsersWithRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RoleID is the roleID argument value.
			RoleID uint
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.AdminRole
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.AdminRole
		}
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
			// Preloads is the preloads argument value.
			Preloads []pkgrepository.Association
		}
		// FindByIDForUpdate holds details about calls to the FindByIDForUpdate method.
		FindByIDForUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// FindByName holds details about calls to the FindByName method.
		FindByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.AdminRole
		}
	}
	lockCount              sync.RWMutex
	lockCountUsersWithRole sync.RWMutex
	lockCreate             sync.RWMutex
	lockDelete             sync.RWMutex
	lockFindAll            sync.RWMutex
	lockFindByID           sync.RWMutex
	lockFindByIDForUpdate  sync.RWMutex
	lockFindByName         sync.RWMutex
	lockUpdate             sync.RWMutex
}

// Count calls CountFunc.
func (mock *AdminRoleRepositoryMock) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	if mock.CountFunc == nil {
		panic("AdminRoleRepositoryMock.CountFunc: method is nil but AdminRoleRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, pg)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedAdminRoleRepository.CountCalls())
func (mock *AdminRoleRepositoryMock) CountCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// CountUsersWithRole calls CountUsersWithRoleFunc.
func (mock *AdminRoleRepositoryMock) CountUsersWithRole(ctx context.Context, roleID uint) (int64, error) {
	if mock.CountUsersWithRoleFunc == nil {
		panic("AdminRoleRepositoryMock.CountUsersWithRoleFunc: method is nil but AdminRoleRepository.CountUsersWithRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		RoleID uint
	}{
		Ctx:    ctx,
		RoleID: roleID,
	}
	mock.lockCountUsersWithRole.Lock()
	mock.calls.CountUsersWithRole = append(mock.calls.CountUsersWithRole, callInfo)
	mock.lockCountUsersWithRole.Unlock()
	return mock.CountUsersWithRoleFunc(ctx, roleID)
}

// CountUsersWithRoleCalls gets all the calls that were made to CountUsersWithRole.
// Check the length with:
//
//	len(mockedAdminRoleRepository.CountUsersWithRoleCalls())
func (mock *AdminRoleRepositoryMock) CountUsersWithRoleCalls() []struct {
	Ctx    context.Context
	RoleID uint
} {
	var calls []struct {
		Ctx    context.Context
		RoleID uint
	}
	mock.lockCountUsersWithRole.RLock()
	calls = mock.calls.CountUsersWithRole
	mock.lockCountUsersWithRole.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *AdminRoleRepositoryMock) Create(ctx context.Context, entity *models.AdminRole) error {
	if mock.CreateFunc == nil {
		panic("AdminRoleRepositoryMock.CreateFunc: method is nil but AdminRoleRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.AdminRole
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAdminRoleRepository.CreateCalls())
func (mock *AdminRoleRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *models.AdminRole
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.AdminRole
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *AdminRoleRepositoryMock) Delete(ctx context.Context, entity *models.AdminRole) error {
	if mock.DeleteFunc == nil {
		panic("AdminRoleRepositoryMock.DeleteFunc: method is nil but AdminRoleRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.AdminRole
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, entity)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAdminRoleRepository.DeleteCalls())
func (mock *AdminRoleRepositoryMock) DeleteCalls() []struct {
	Ctx    context.Context
	Entity *models.AdminRole
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.AdminRole
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindAll calls FindAllFunc.
func (mock *AdminRoleRepositoryMock) FindAll(ctx context.Context, pg *pagination.Pagination) ([]*models.AdminRole, error) {
	if mock.FindAllFunc == nil {
		panic("AdminRoleRepositoryMock.FindAllFunc: method is nil but AdminRoleRepository.FindAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	mock.lockFindAll.Unlock()
	return mock.FindAllFunc(ctx, pg)
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//
//	len(mockedAdminRoleRepository.FindAllCalls())
func (mock *AdminRoleRepositoryMock) FindAllCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockFindAll.RLock()
	calls = mock.calls.FindAll
	mock.lockFindAll.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *AdminRoleRepositoryMock) FindByID(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.AdminRole, error) {
	if mock.FindByIDFunc == nil {
		panic("AdminRoleRepositoryMock.FindByIDFunc: method is nil but AdminRoleRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}{
		Ctx:      ctx,
		ID:       id,
		Preloads: preloads,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id, preloads...)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedAdminRoleRepository.FindByIDCalls())
func (mock *AdminRoleRepositoryMock) FindByIDCalls() []struct {
	Ctx      context.Context
	ID       uint
	Preloads []pkgrepository.Association
} {
	var calls []struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindByIDForUpdate calls FindByIDForUpdateFunc.
func (mock *AdminRoleRepositoryMock) FindByIDForUpdate(ctx context.Context, id uint) (*models.AdminRole, error) {
	if mock.FindByIDForUpdateFunc == nil {
		panic("AdminRoleRepositoryMock.FindByIDForUpdateFunc: method is nil but AdminRoleRepository.FindByIDForUpdate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFindByIDForUpdate.Lock()
	mock.calls.FindByIDForUpdate = append(mock.calls.FindByIDForUpdate, callInfo)
	mock.lockFindByIDForUpdate.Unlock()
	return mock.FindByIDForUpdateFunc(ctx, id)
}

// FindByIDForUpdateCalls gets all the calls that were made to FindByIDForUpdate.
// Check the length with:
//
//	len(mockedAdminRoleRepository.FindByIDForUpdateCalls())
func (mock *AdminRoleRepositoryMock) FindByIDForUpdateCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockFindByIDForUpdate.RLock()
	calls = mock.calls.FindByIDForUpdate
	mock.lockFindByIDForUpdate.RUnlock()
	return calls
}

// FindByName calls FindByNameFunc.
func (mock *AdminRoleRepositoryMock) FindByName(ctx context.Context, name string) (*models.AdminRole, error) {
	if mock.FindByNameFunc == nil {
		panic("AdminRoleRepositoryMock.FindByNameFunc: method is nil but AdminRoleRepository.FindByName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockFindByName.Lock()
	mock.calls.FindByName = append(mock.calls.FindByName, callInfo)
	mock.lockFindByName.Unlock()
	return mock.FindByNameFunc(ctx, name)
}

// FindByNameCalls gets all the calls that were made to FindByName.
// Check the length with:
//
//	len(mockedAdminRoleRepository.FindByNameCalls())
func (mock *AdminRoleRepositoryMock) FindByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockFindByName.RLock()
	calls = mock.calls.FindByName
	mock.lockFindByName.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *AdminRoleRepositoryMock) Update(ctx context.Context, entity *models.AdminRole) error {
	if mock.UpdateFunc == nil {
		panic("AdminRoleRepositoryMock.UpdateFunc: method is nil but AdminRoleRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.AdminRole
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, entity)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedAdminRoleRepository.UpdateCalls())
func (mock *AdminRoleRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Entity *models.AdminRole
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.AdminRole
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
