// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/dto"
	"github.com/PhantomX7/athleton/internal/models"
	"github.com/PhantomX7/athleton/internal/modules/config/service"
	"github.com/PhantomX7/athleton/pkg/pagination"
	"github.com/PhantomX7/athleton/pkg/response"
)

// Ensure, that ConfigServiceMock does implement service.ConfigService.
// If this is not the case, regenerate this file with moq.
var _ service.ConfigService = &ConfigServiceMock{}

// ConfigServiceMock is a mock implementation of service.ConfigService.
//
//	func TestSomethingThatUsesConfigService(t *testing.T) {
//
//		// make and configure a mocked service.ConfigService
//		mockedConfigService := &ConfigServiceMock{
//			FindByKeyFunc: func(ctx context.Context, configKey string) (*models.Config, error) {
//				panic("mock out the FindByKey method")
//			},
//			FindPublicByKeyFunc: func(ctx context.Context, configKey string) (*models.Config, error) {
//				panic("mock out the FindPublicByKey method")
//			},
//			IndexFunc: func(ctx context.Context, req *pagination.Pagination) ([]*models.Config, response.Meta, error) {
//				panic("mock out the Index method")
//			},
//			PublicIndexFunc: func(ctx context.Context, req *pagination.Pagination) ([]*models.Config, response.Meta, error) {
//				panic("mock out the PublicIndex method")
//			},
//			UpdateFunc: func(ctx context.Context, configID uint, req *dto.ConfigUpdateRequest) (*models.Config, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedConfigService in code that requires service.ConfigService
//		// and then make assertions.
//
//	}
type ConfigServiceMock struct {
	// FindByKeyFunc mocks the FindByKey method.
	FindByKeyFunc func(ctx context.Context, configKey string) (*models.Config, error)

	// FindPublicByKeyFunc mocks the FindPublicByKey method.
	FindPublicByKeyFunc func(ctx context.Context, configKey string) (*models.Config, error)

	// IndexFunc mocks the Index method.
	IndexFunc func(ctx context.Context, req *pagination.Pagination) ([]*models.Config, response.Meta, error)

	// PublicIndexFunc mocks the PublicIndex method.
	PublicIndexFunc func(ctx context.Context, req *pagination.Pagination) ([]*models.Config, response.Meta, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, configID uint, req *dto.ConfigUpdateRequest) (*models.Config, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByKey holds details about calls to the FindByKey method.
		FindByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigKey is the configKey argument value.
			ConfigKey string
		}
		// FindPublicByKey holds details about calls to the FindPublicByKey method.
		FindPublicByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigKey is the configKey argument value.
			ConfigKey string
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *pagination.Pagination
		}
		// PublicIndex holds details about calls to the PublicIndex method.
		PublicIndex []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *pagination.Pagination
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigID is the configID argument value.
			ConfigID uint
			// Req is the req argument value.
			Req *dto.ConfigUpdateRequest
		}
	}
	lockFindByKey       sync.RWMutex
	lockFindPublicByKey sync.RWMutex
	lockIndex           sync.RWMutex
	lockPublicIndex     sync.RWMutex
	lockUpdate          sync.RWMutex
}

// FindByKey calls FindByKeyFunc.
func (mock *ConfigServiceMock) FindByKey(ctx context.Context, configKey string) (*models.Config, error) {
	if mock.FindByKeyFunc == nil {
		panic("ConfigServiceMock.FindByKeyFunc: method is nil but ConfigService.FindByKey was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ConfigKey string
	}{
		Ctx:       ctx,
		ConfigKey: configKey,
	}
	mock.lockFindByKey.Lock()
	mock.calls.FindByKey = append(mock.calls.FindByKey, callInfo)
	mock.lockFindByKey.Unlock()
	return mock.FindByKeyFunc(ctx, configKey)
}

// FindByKeyCalls gets all the calls that were made to FindByKey.
// Check the length with:
//
//	len(mockedConfigService.FindByKeyCalls())
func (mock *ConfigServiceMock) FindByKeyCalls() []struct {
	Ctx       context.Context
	ConfigKey string
} {
	var calls []struct {
		Ctx       context.Context
		ConfigKey string
	}
	mock.lockFindByKey.RLock()
	calls = mock.calls.FindByKey
	mock.lockFindByKey.RUnlock()
	return calls
}

// FindPublicByKey calls FindPublicByKeyFunc.
func (mock *ConfigServiceMock) FindPublicByKey(ctx context.Context, configKey string) (*models.Config, error) {
	if mock.FindPublicByKeyFunc == nil {
		panic("ConfigServiceMock.FindPublicByKeyFunc: method is nil but ConfigService.FindPublicByKey was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ConfigKey string
	}{
		Ctx:       ctx,
		ConfigKey: configKey,
	}
	mock.lockFindPublicByKey.Lock()
	mock.calls.FindPublicByKey = append(mock.calls.FindPublicByKey, callInfo)
	mock.lockFindPublicByKey.Unlock()
	return mock.FindPublicByKeyFunc(ctx, configKey)
}

// FindPublicByKeyCalls gets all the calls that were made to FindPublicByKey.
// Check the length with:
//
//	len(mockedConfigService.FindPublicByKeyCalls())
func (mock *ConfigServiceMock) FindPublicByKeyCalls() []struct {
	Ctx       context.Context
	ConfigKey string
} {
	var calls []struct {
		Ctx       context.Context
		ConfigKey string
	}
	mock.lockFindPublicByKey.RLock()
	calls = mock.calls.FindPublicByKey
	mock.lockFindPublicByKey.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *ConfigServiceMock) Index(ctx context.Context, req *pagination.Pagination) ([]*models.Config, response.Meta, error) {
	if mock.IndexFunc == nil {
		panic("ConfigServiceMock.IndexFunc: method is nil but ConfigService.Index was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *pagination.Pagination
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(ctx, req)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedConfigService.IndexCalls())
func (mock *ConfigServiceMock) IndexCalls() []struct {
	Ctx context.Context
	Req *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Req *pagination.Pagination
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// PublicIndex calls PublicIndexFunc.
func (mock *ConfigServiceMock) PublicIndex(ctx context.Context, req *pagination.Pagination) ([]*models.Config, response.Meta, error) {
	if mock.PublicIndexFunc == nil {
		panic("ConfigServiceMock.PublicIndexFunc: method is nil but ConfigService.PublicIndex was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *pagination.Pagination
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPublicIndex.Lock()
	mock.calls.PublicIndex = append(mock.calls.PublicIndex, callInfo)
	mock.lockPublicIndex.Unlock()
	return mock.PublicIndexFunc(ctx, req)
}

// PublicIndexCalls gets all the calls that were made to PublicIndex.
// Check the length with:
//
//	len(mockedConfigService.PublicIndexCalls())
func (mock *ConfigServiceMock) PublicIndexCalls() []struct {
	Ctx context.Context
	Req *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Req *pagination.Pagination
	}
	mock.lockPublicIndex.RLock()
	calls = mock.calls.PublicIndex
	mock.lockPublicIndex.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ConfigServiceMock) Update(ctx context.Context, configID uint, req *dto.ConfigUpdateRequest) (*models.Config, error) {
	if mock.UpdateFunc == nil {
		panic("ConfigServiceMock.UpdateFunc: method is nil but ConfigService.Update was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ConfigID uint
		Req      *dto.ConfigUpdateRequest
	}{
		Ctx:      ctx,
		ConfigID: configID,
		Req:      req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, configID, req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedConfigService.UpdateCalls())
func (mock *ConfigServiceMock) UpdateCalls() []struct {
	Ctx      context.Context
	ConfigID uint
	Req      *dto.ConfigUpdateRequest
} {
	var calls []struct {
		Ctx      context.Context
		ConfigID uint
		Req      *dto.ConfigUpdateRequest
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
