// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/libs/transaction_manager"
)

// Ensure, that TransactionManagerMock does implement transaction_manager.TransactionManager.
// If this is not the case, regenerate this file with moq.
var _ transaction_manager.TransactionManager = &TransactionManagerMock{}

// TransactionManagerMock is a mock implementation of transaction_manager.TransactionManager.
//
//	func TestSomethingThatUsesTransactionManager(t *testing.T) {
//
//		// make and configure a mocked transaction_manager.TransactionManager
//		mockedTransactionManager := &TransactionManagerMock{
//			ExecuteInTransactionFunc: func(ctx context.Context, fn func(ctx context.Context) error) error {
//				panic("mock out the ExecuteInTransaction method")
//			},
//		}
//
//		// use mockedTransactionManager in code that requires transaction_manager.TransactionManager
//		// and then make assertions.
//
//	}
type TransactionManagerMock struct {
	// ExecuteInTransactionFunc mocks the ExecuteInTransaction method.
	ExecuteInTransactionFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// ExecuteInTransaction holds details about calls to the ExecuteInTransaction method.
		ExecuteInTransaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockExecuteInTransaction sync.RWMutex
}

// ExecuteInTransaction calls ExecuteInTransactionFunc.
func (mock *TransactionManagerMock) ExecuteInTransaction(ctx context.Context, fn func(ctx context.Context) error) error {
	if mock.ExecuteInTransactionFunc == nil {
		panic("TransactionManagerMock.ExecuteInTransactionFunc: method is nil but TransactionManager.ExecuteInTransaction was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockExecuteInTransaction.Lock()
	mock.calls.ExecuteInTransaction = append(mock.calls.ExecuteInTransaction, callInfo)
	mock.lockExecuteInTransaction.Unlock()
	return mock.ExecuteInTransactionFunc(ctx, fn)
}

// ExecuteInTransactionCalls gets all the calls that were made to ExecuteInTransaction.
// Check the length with:
//
//	len(mockedTransactionManager.ExecuteInTransactionCalls())
func (mock *TransactionManagerMock) ExecuteInTransactionCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}
	mock.lockExecuteInTransaction.RLock()
	calls = mock.calls.ExecuteInTransaction
	mock.lockExecuteInTransaction.RUnlock()
	return calls
}
