// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/models"
	logrepository "github.com/PhantomX7/athleton/internal/modules/log/repository"
	"github.com/PhantomX7/athleton/pkg/pagination"
	pkgrepository "github.com/PhantomX7/athleton/pkg/repository"
)

// Ensure, that LogRepositoryMock does implement logrepository.LogRepository.
// If this is not the case, regenerate this file with moq.
var _ logrepository.LogRepository = &LogRepositoryMock{}

// LogRepositoryMock is a mock implementation of logrepository.LogRepository.
//
//	func TestSomethingThatUsesLogRepository(t *testing.T) {
//
//		// make and configure a mocked logrepository.LogRepository
//		mockedLogRepository := &LogRepositoryMock{
//			CountFunc: func(ctx context.Context, pg *pagination.Pagination) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, entity *models.Log) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, entity *models.Log) error {
//				panic("mock out the Delete method")
//			},
//			FindAllFunc: func(ctx context.Context, pg *pagination.Pagination) ([]*models.Log, error) {
//				panic("mock out the FindAll method")
//			},
//			FindByIDFunc: func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.Log, error) {
//				panic("mock out the FindByID method")
//			},
//			UpdateFunc: func(ctx context.Context, entity *models.Log) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedLogRepository in code that requires logrepository.LogRepository
//		// and then make assertions.
//
//	}
type LogRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, pg *pagination.Pagination) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *models.Log) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, entity *models.Log) error

	// FindAllFunc mocks the FindAll method.
	FindAllFunc func(ctx context.Context, pg *pagination.Pagination) ([]*models.Log, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.Log, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, entity *models.Log) error

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.Log
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.Log
		}
		// FindAll holds details about calls to the FindAll method.
		FindAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pg is the pg argument value.
			Pg *pagination.Pagination
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
			// Preloads is the preloads argument value.
			Preloads []pkgrepository.Association
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *models.Log
		}
	}
	lockCount    sync.RWMutex
	lockCreate   sync.RWMutex
	lockDelete   sync.RWMutex
	lockFindAll  sync.RWMutex
	lockFindByID sync.RWMutex
	lockUpdate   sync.RWMutex
}

// Count calls CountFunc.
func (mock *LogRepositoryMock) Count(ctx context.Context, pg *pagination.Pagination) (int64, error) {
	if mock.CountFunc == nil {
		panic("LogRepositoryMock.CountFunc: method is nil but LogRepository.Count was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	return mock.CountFunc(ctx, pg)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedLogRepository.CountCalls())
func (mock *LogRepositoryMock) CountCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *LogRepositoryMock) Create(ctx context.Context, entity *models.Log) error {
	if mock.CreateFunc == nil {
		panic("LogRepositoryMock.CreateFunc: method is nil but LogRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.Log
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedLogRepository.CreateCalls())
func (mock *LogRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *models.Log
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.Log
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *LogRepositoryMock) Delete(ctx context.Context, entity *models.Log) error {
	if mock.DeleteFunc == nil {
		panic("LogRepositoryMock.DeleteFunc: method is nil but LogRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.Log
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, entity)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedLogRepository.DeleteCalls())
func (mock *LogRepositoryMock) DeleteCalls() []struct {
	Ctx    context.Context
	Entity *models.Log
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.Log
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindAll calls FindAllFunc.
func (mock *LogRepositoryMock) FindAll(ctx context.Context, pg *pagination.Pagination) ([]*models.Log, error) {
	if mock.FindAllFunc == nil {
		panic("LogRepositoryMock.FindAllFunc: method is nil but LogRepository.FindAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}{
		Ctx: ctx,
		Pg:  pg,
	}
	mock.lockFindAll.Lock()
	mock.calls.FindAll = append(mock.calls.FindAll, callInfo)
	mock.lockFindAll.Unlock()
	return mock.FindAllFunc(ctx, pg)
}

// FindAllCalls gets all the calls that were made to FindAll.
// Check the length with:
//
//	len(mockedLogRepository.FindAllCalls())
func (mock *LogRepositoryMock) FindAllCalls() []struct {
	Ctx context.Context
	Pg  *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Pg  *pagination.Pagination
	}
	mock.lockFindAll.RLock()
	calls = mock.calls.FindAll
	mock.lockFindAll.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *LogRepositoryMock) FindByID(ctx context.Context, id uint, preloads ...pkgrepository.Association) (*models.Log, error) {
	if mock.FindByIDFunc == nil {
		panic("LogRepositoryMock.FindByIDFunc: method is nil but LogRepository.FindByID was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}{
		Ctx:      ctx,
		ID:       id,
		Preloads: preloads,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, id, preloads...)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedLogRepository.FindByIDCalls())
func (mock *LogRepositoryMock) FindByIDCalls() []struct {
	Ctx      context.Context
	ID       uint
	Preloads []pkgrepository.Association
} {
	var calls []struct {
		Ctx      context.Context
		ID       uint
		Preloads []pkgrepository.Association
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *LogRepositoryMock) Update(ctx context.Context, entity *models.Log) error {
	if mock.UpdateFunc == nil {
		panic("LogRepositoryMock.UpdateFunc: method is nil but LogRepository.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *models.Log
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, entity)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedLogRepository.UpdateCalls())
func (mock *LogRepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Entity *models.Log
} {
	var calls []struct {
		Ctx    context.Context
		Entity *models.Log
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
