// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/dto"
	"github.com/PhantomX7/athleton/internal/models"
	"github.com/PhantomX7/athleton/internal/modules/user/service"
	"github.com/PhantomX7/athleton/pkg/pagination"
	"github.com/PhantomX7/athleton/pkg/response"
)

// Ensure, that UserServiceMock does implement service.UserService.
// If this is not the case, regenerate this file with moq.
var _ service.UserService = &UserServiceMock{}

// UserServiceMock is a mock implementation of service.UserService.
//
//	func TestSomethingThatUsesUserService(t *testing.T) {
//
//		// make and configure a mocked service.UserService
//		mockedUserService := &UserServiceMock{
//			AssignAdminRoleFunc: func(ctx context.Context, userID uint, req *dto.UserAssignAdminRoleRequest) (*models.User, error) {
//				panic("mock out the AssignAdminRole method")
//			},
//			ChangePasswordFunc: func(ctx context.Context, userID uint, req *dto.ChangeAdminPasswordRequest) error {
//				panic("mock out the ChangePassword method")
//			},
//			CreateFunc: func(ctx context.Context, req *dto.AdminUserCreateRequest) (*models.User, error) {
//				panic("mock out the Create method")
//			},
//			FindByIDFunc: func(ctx context.Context, userID uint) (*models.User, error) {
//				panic("mock out the FindByID method")
//			},
//			IndexFunc: func(ctx context.Context, req *pagination.Pagination) ([]*models.User, response.Meta, error) {
//				panic("mock out the Index method")
//			},
//			UpdateFunc: func(ctx context.Context, userID uint, req *dto.UserUpdateRequest) (*models.User, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserService in code that requires service.UserService
//		// and then make assertions.
//
//	}
type UserServiceMock struct {
	// AssignAdminRoleFunc mocks the AssignAdminRole method.
	AssignAdminRoleFunc func(ctx context.Context, userID uint, req *dto.UserAssignAdminRoleRequest) (*models.User, error)

	// ChangePasswordFunc mocks the ChangePassword method.
	ChangePasswordFunc func(ctx context.Context, userID uint, req *dto.ChangeAdminPasswordRequest) error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, req *dto.AdminUserCreateRequest) (*models.User, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, userID uint) (*models.User, error)

	// IndexFunc mocks the Index method.
	IndexFunc func(ctx context.Context, req *pagination.Pagination) ([]*models.User, response.Meta, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, userID uint, req *dto.UserUpdateRequest) (*models.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// AssignAdminRole holds details about calls to the AssignAdminRole method.
		AssignAdminRole []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
			// Req is the req argument value.
			Req *dto.UserAssignAdminRoleRequest
		}
		// ChangePassword holds details about calls to the ChangePassword method.
		ChangePassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
			// Req is the req argument value.
			Req *dto.ChangeAdminPasswordRequest
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *dto.AdminUserCreateRequest
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
		}
		// Index holds details about calls to the Index method.
		Index []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *pagination.Pagination
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uint
			// Req is the req argument value.
			Req *dto.UserUpdateRequest
		}
	}
	lockAssignAdminRole sync.RWMutex
	lockChangePassword  sync.RWMutex
	lockCreate          sync.RWMutex
	lockFindByID        sync.RWMutex
	lockIndex           sync.RWMutex
	lockUpdate          sync.RWMutex
}

// AssignAdminRole calls AssignAdminRoleFunc.
func (mock *UserServiceMock) AssignAdminRole(ctx context.Context, userID uint, req *dto.UserAssignAdminRoleRequest) (*models.User, error) {
	if mock.AssignAdminRoleFunc == nil {
		panic("UserServiceMock.AssignAdminRoleFunc: method is nil but UserService.AssignAdminRole was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
		Req    *dto.UserAssignAdminRoleRequest
	}{
		Ctx:    ctx,
		UserID: userID,
		Req:    req,
	}
	mock.lockAssignAdminRole.Lock()
	mock.calls.AssignAdminRole = append(mock.calls.AssignAdminRole, callInfo)
	mock.lockAssignAdminRole.Unlock()
	return mock.AssignAdminRoleFunc(ctx, userID, req)
}

// AssignAdminRoleCalls gets all the calls that were made to AssignAdminRole.
// Check the length with:
//
//	len(mockedUserService.AssignAdminRoleCalls())
func (mock *UserServiceMock) AssignAdminRoleCalls() []struct {
	Ctx    context.Context
	UserID uint
	Req    *dto.UserAssignAdminRoleRequest
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
		Req    *dto.UserAssignAdminRoleRequest
	}
	mock.lockAssignAdminRole.RLock()
	calls = mock.calls.AssignAdminRole
	mock.lockAssignAdminRole.RUnlock()
	return calls
}

// ChangePassword calls ChangePasswordFunc.
func (mock *UserServiceMock) ChangePassword(ctx context.Context, userID uint, req *dto.ChangeAdminPasswordRequest) error {
	if mock.ChangePasswordFunc == nil {
		panic("UserServiceMock.ChangePasswordFunc: method is nil but UserService.ChangePassword was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
		Req    *dto.ChangeAdminPasswordRequest
	}{
		Ctx:    ctx,
		UserID: userID,
		Req:    req,
	}
	mock.lockChangePassword.Lock()
	mock.calls.ChangePassword = append(mock.calls.ChangePassword, callInfo)
	mock.lockChangePassword.Unlock()
	return mock.ChangePasswordFunc(ctx, userID, req)
}

// ChangePasswordCalls gets all the calls that were made to ChangePassword.
// Check the length with:
//
//	len(mockedUserService.ChangePasswordCalls())
func (mock *UserServiceMock) ChangePasswordCalls() []struct {
	Ctx    context.Context
	UserID uint
	Req    *dto.ChangeAdminPasswordRequest
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
		Req    *dto.ChangeAdminPasswordRequest
	}
	mock.lockChangePassword.RLock()
	calls = mock.calls.ChangePassword
	mock.lockChangePassword.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *UserServiceMock) Create(ctx context.Context, req *dto.AdminUserCreateRequest) (*models.User, error) {
	if mock.CreateFunc == nil {
		panic("UserServiceMock.CreateFunc: method is nil but UserService.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *dto.AdminUserCreateRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, req)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserService.CreateCalls())
func (mock *UserServiceMock) CreateCalls() []struct {
	Ctx context.Context
	Req *dto.AdminUserCreateRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *dto.AdminUserCreateRequest
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *UserServiceMock) FindByID(ctx context.Context, userID uint) (*models.User, error) {
	if mock.FindByIDFunc == nil {
		panic("UserServiceMock.FindByIDFunc: method is nil but UserService.FindByID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, userID)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserService.FindByIDCalls())
func (mock *UserServiceMock) FindByIDCalls() []struct {
	Ctx    context.Context
	UserID uint
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// Index calls IndexFunc.
func (mock *UserServiceMock) Index(ctx context.Context, req *pagination.Pagination) ([]*models.User, response.Meta, error) {
	if mock.IndexFunc == nil {
		panic("UserServiceMock.IndexFunc: method is nil but UserService.Index was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *pagination.Pagination
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockIndex.Lock()
	mock.calls.Index = append(mock.calls.Index, callInfo)
	mock.lockIndex.Unlock()
	return mock.IndexFunc(ctx, req)
}

// IndexCalls gets all the calls that were made to Index.
// Check the length with:
//
//	len(mockedUserService.IndexCalls())
func (mock *UserServiceMock) IndexCalls() []struct {
	Ctx context.Context
	Req *pagination.Pagination
} {
	var calls []struct {
		Ctx context.Context
		Req *pagination.Pagination
	}
	mock.lockIndex.RLock()
	calls = mock.calls.Index
	mock.lockIndex.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserServiceMock) Update(ctx context.Context, userID uint, req *dto.UserUpdateRequest) (*models.User, error) {
	if mock.UpdateFunc == nil {
		panic("UserServiceMock.UpdateFunc: method is nil but UserService.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID uint
		Req    *dto.UserUpdateRequest
	}{
		Ctx:    ctx,
		UserID: userID,
		Req:    req,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, userID, req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserService.UpdateCalls())
func (mock *UserServiceMock) UpdateCalls() []struct {
	Ctx    context.Context
	UserID uint
	Req    *dto.UserUpdateRequest
} {
	var calls []struct {
		Ctx    context.Context
		UserID uint
		Req    *dto.UserUpdateRequest
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
