// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/PhantomX7/athleton/internal/modules/cron/service"
)

// Ensure, that CronServiceMock does implement service.CronService.
// If this is not the case, regenerate this file with moq.
var _ service.CronService = &CronServiceMock{}

// CronServiceMock is a mock implementation of service.CronService.
//
//	func TestSomethingThatUsesCronService(t *testing.T) {
//
//		// make and configure a mocked service.CronService
//		mockedCronService := &CronServiceMock{
//			ClearRefreshTokenFunc: func(ctx context.Context) error {
//				panic("mock out the ClearRefreshToken method")
//			},
//			RunAllCleanupJobsFunc: func(ctx context.Context) error {
//				panic("mock out the RunAllCleanupJobs method")
//			},
//		}
//
//		// use mockedCronService in code that requires service.CronService
//		// and then make assertions.
//
//	}
type CronServiceMock struct {
	// ClearRefreshTokenFunc mocks the ClearRefreshToken method.
	ClearRefreshTokenFunc func(ctx context.Context) error

	// RunAllCleanupJobsFunc mocks the RunAllCleanupJobs method.
	RunAllCleanupJobsFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// ClearRefreshToken holds details about calls to the ClearRefreshToken method.
		ClearRefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RunAllCleanupJobs holds details about calls to the RunAllCleanupJobs method.
		RunAllCleanupJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockClearRefreshToken sync.RWMutex
	lockRunAllCleanupJobs sync.RWMutex
}

// ClearRefreshToken calls ClearRefreshTokenFunc.
func (mock *CronServiceMock) ClearRefreshToken(ctx context.Context) error {
	if mock.ClearRefreshTokenFunc == nil {
		panic("CronServiceMock.ClearRefreshTokenFunc: method is nil but CronService.ClearRefreshToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClearRefreshToken.Lock()
	mock.calls.ClearRefreshToken = append(mock.calls.ClearRefreshToken, callInfo)
	mock.lockClearRefreshToken.Unlock()
	return mock.ClearRefreshTokenFunc(ctx)
}

// ClearRefreshTokenCalls gets all the calls that were made to ClearRefreshToken.
// Check the length with:
//
//	len(mockedCronService.ClearRefreshTokenCalls())
func (mock *CronServiceMock) ClearRefreshTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClearRefreshToken.RLock()
	calls = mock.calls.ClearRefreshToken
	mock.lockClearRefreshToken.RUnlock()
	return calls
}

// RunAllCleanupJobs calls RunAllCleanupJobsFunc.
func (mock *CronServiceMock) RunAllCleanupJobs(ctx context.Context) error {
	if mock.RunAllCleanupJobsFunc == nil {
		panic("CronServiceMock.RunAllCleanupJobsFunc: method is nil but CronService.RunAllCleanupJobs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRunAllCleanupJobs.Lock()
	mock.calls.RunAllCleanupJobs = append(mock.calls.RunAllCleanupJobs, callInfo)
	mock.lockRunAllCleanupJobs.Unlock()
	return mock.RunAllCleanupJobsFunc(ctx)
}

// RunAllCleanupJobsCalls gets all the calls that were made to RunAllCleanupJobs.
// Check the length with:
//
//	len(mockedCronService.RunAllCleanupJobsCalls())
func (mock *CronServiceMock) RunAllCleanupJobsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRunAllCleanupJobs.RLock()
	calls = mock.calls.RunAllCleanupJobs
	mock.lockRunAllCleanupJobs.RUnlock()
	return calls
}
